# Generated by Django 5.0.3 on 2024-03-10 00:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Administrador',
            fields=[
                ('id_administrador', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=50)),
                ('apellido', models.CharField(max_length=50)),
                ('ci', models.CharField(max_length=10, unique=True)),
                ('contrasenia', models.CharField(max_length=15)),
            ],
        ),
        migrations.CreateModel(
            name='Alimento',
            fields=[
                ('id_alimento', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=50)),
                ('calorias', models.IntegerField()),
                ('grasa_total_g', models.IntegerField()),
                ('proteina_g', models.DecimalField(decimal_places=2, max_digits=5)),
                ('sodio_mg', models.DecimalField(decimal_places=2, max_digits=5)),
                ('potasio_mg', models.DecimalField(decimal_places=2, max_digits=5)),
                ('colesterol_mg', models.DecimalField(decimal_places=2, max_digits=5)),
                ('total_carbohidratos_g', models.DecimalField(decimal_places=2, max_digits=5)),
                ('total_fibra_g', models.DecimalField(decimal_places=2, max_digits=5)),
                ('azucar_total_g', models.DecimalField(decimal_places=2, max_digits=5)),
                ('grasa_total_saturada_g', models.DecimalField(decimal_places=2, max_digits=5)),
                ('tamaño_porcion_g', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id_cliente', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=50)),
                ('apellido', models.CharField(max_length=50)),
                ('ci', models.CharField(max_length=10, unique=True)),
                ('contrasenia', models.CharField(max_length=15)),
                ('edad', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Genero',
            fields=[
                ('id_genero', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=9)),
            ],
        ),
        migrations.CreateModel(
            name='nivelActividad',
            fields=[
                ('id_nivel_actividad', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='nivelGym',
            fields=[
                ('id_nivel_gym', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Objetivo',
            fields=[
                ('id_objetivo', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Consume',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField()),
                ('id_alimento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='routine_app.alimento')),
                ('id_cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='routine_app.cliente')),
            ],
        ),
        migrations.CreateModel(
            name='Entrenador',
            fields=[
                ('id_entrenador', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=50)),
                ('apellido', models.CharField(max_length=50)),
                ('ci', models.CharField(max_length=10, unique=True)),
                ('contrasenia', models.CharField(max_length=15)),
                ('id_administrador', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='routine_app.administrador')),
            ],
        ),
        migrations.AddField(
            model_name='cliente',
            name='id_entrenador',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='routine_app.entrenador'),
        ),
        migrations.AddField(
            model_name='cliente',
            name='id_genero',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='routine_app.genero'),
        ),
        migrations.AddField(
            model_name='cliente',
            name='id_nivel_actividad',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='routine_app.nivelactividad'),
        ),
        migrations.AddField(
            model_name='cliente',
            name='id_nivel_gym',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='routine_app.nivelgym'),
        ),
        migrations.AddField(
            model_name='cliente',
            name='id_objetivo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='routine_app.objetivo'),
        ),
    ]
