# Generated by Django 4.2.7 on 2024-03-13 00:04

from django.db import migrations


def crear_generos(apps,schema_editor):
    Genero = apps.get_model('routine_app', 'Genero')
    generos = ['Masculino','Femenino']
    for genero in generos:
        Genero.objects.create(nombre = genero)


def revertir_crear_genero(apps,schema_editor):
    Genero = apps.get_model('routine_app','Genero')
    Genero.objects.filter(nombre__in=['Masculino','Femenino']).delete()


class Migration(migrations.Migration):

    dependencies = [
        ('routine_app', '0004_llenar_niveles_actividad'),
    ]

    operations = [
        migrations.RunPython(crear_generos, revertir_crear_genero)
    ]
