# Generated by Django 5.0.3 on 2024-11-24 01:10

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('routine_app', '0007_llenar_nivelesActividadFactor'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Compuesta',
            fields=[
                ('id_compuesta', models.AutoField(primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='Dispone',
            fields=[
                ('id_dispone', models.AutoField(primary_key=True, serialize=False)),
                ('fecha', models.DateField(auto_now_add=True)),
                ('cantidad', models.IntegerField()),
                ('tamaño_porcion_g', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Ejercicio',
            fields=[
                ('id_ejercicio', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=200)),
                ('musculo', models.CharField(max_length=200)),
                ('equipamento', models.CharField(max_length=1000)),
                ('instrucciones', models.JSONField(max_length=1000)),
                ('imagen', models.URLField(blank=True, max_length=500, null=True)),
                ('objetivo', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='ParteDia',
            fields=[
                ('id_parte_dia', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=30)),
                ('icono', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Rutina',
            fields=[
                ('id_rutina', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=50)),
                ('descripcion', models.CharField(max_length=200)),
                ('enfoque', models.CharField(max_length=50)),
                ('tipo', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='SeAsigna',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('serie', models.IntegerField()),
                ('repeticiones', models.IntegerField()),
                ('peso', models.IntegerField()),
                ('fecha', models.DateField(auto_now_add=True)),
                ('dia', models.CharField(max_length=30)),
            ],
        ),
        migrations.RemoveField(
            model_name='administrador',
            name='ci',
        ),
        migrations.RemoveField(
            model_name='administrador',
            name='contrasenia',
        ),
        migrations.RemoveField(
            model_name='alimento',
            name='azucar_total_g',
        ),
        migrations.RemoveField(
            model_name='alimento',
            name='colesterol_mg',
        ),
        migrations.RemoveField(
            model_name='alimento',
            name='grasa_total_g',
        ),
        migrations.RemoveField(
            model_name='alimento',
            name='grasa_total_saturada_g',
        ),
        migrations.RemoveField(
            model_name='alimento',
            name='potasio_mg',
        ),
        migrations.RemoveField(
            model_name='alimento',
            name='sodio_mg',
        ),
        migrations.RemoveField(
            model_name='alimento',
            name='tamaño_porcion_g',
        ),
        migrations.RemoveField(
            model_name='alimento',
            name='total_carbohidratos_g',
        ),
        migrations.RemoveField(
            model_name='alimento',
            name='total_fibra_g',
        ),
        migrations.RemoveField(
            model_name='cliente',
            name='ci',
        ),
        migrations.RemoveField(
            model_name='cliente',
            name='contrasenia',
        ),
        migrations.RemoveField(
            model_name='cliente',
            name='edad',
        ),
        migrations.RemoveField(
            model_name='entrenador',
            name='ci',
        ),
        migrations.RemoveField(
            model_name='entrenador',
            name='contrasenia',
        ),
        migrations.AddField(
            model_name='administrador',
            name='borrado',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='administrador',
            name='cedula',
            field=models.CharField(default='0000000000', max_length=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='administrador',
            name='user',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='alimento',
            name='api_id_referencia',
            field=models.CharField(default=1, max_length=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='alimento',
            name='carbohidratos_g',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=6),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='alimento',
            name='grasa_g',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=6),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='cliente',
            name='altura',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5),
        ),
        migrations.AddField(
            model_name='cliente',
            name='borrado',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='cliente',
            name='carbohidratos_g',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=7),
        ),
        migrations.AddField(
            model_name='cliente',
            name='cedula',
            field=models.CharField(default='0000000000', max_length=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='cliente',
            name='fecha_nacimiento',
            field=models.DateField(default='01-01-2001'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='cliente',
            name='grasas_g',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=7),
        ),
        migrations.AddField(
            model_name='cliente',
            name='peso',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5),
        ),
        migrations.AddField(
            model_name='cliente',
            name='proteina_g',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=7),
        ),
        migrations.AddField(
            model_name='cliente',
            name='tmb',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=7),
        ),
        migrations.AddField(
            model_name='cliente',
            name='user',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='entrenador',
            name='borrado',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='entrenador',
            name='cedula',
            field=models.CharField(default='0000000000', max_length=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='entrenador',
            name='user',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='nivelactividad',
            name='factor',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='alimento',
            name='calorias',
            field=models.DecimalField(decimal_places=2, max_digits=7),
        ),
        migrations.AlterField(
            model_name='alimento',
            name='nombre',
            field=models.CharField(max_length=150),
        ),
        migrations.AlterField(
            model_name='alimento',
            name='proteina_g',
            field=models.DecimalField(decimal_places=2, max_digits=6),
        ),
        migrations.AlterField(
            model_name='consume',
            name='fecha',
            field=models.DateField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='genero',
            name='nombre',
            field=models.CharField(max_length=10),
        ),
        migrations.AddConstraint(
            model_name='consume',
            constraint=models.UniqueConstraint(fields=('id_cliente', 'id_alimento'), name='unique_cliente_alimento'),
        ),
        migrations.AddField(
            model_name='dispone',
            name='id_alimento',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='alimento_dispone', to='routine_app.alimento'),
        ),
        migrations.AddField(
            model_name='dispone',
            name='id_cliente',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cliente_dispone', to='routine_app.cliente'),
        ),
        migrations.AddField(
            model_name='compuesta',
            name='id_ejercicio',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='routine_app.ejercicio'),
        ),
        migrations.AddField(
            model_name='dispone',
            name='id_parte_dia',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='routine_app.partedia'),
        ),
        migrations.AddField(
            model_name='rutina',
            name='id_entrenador',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='routine_app.entrenador'),
        ),
        migrations.AddField(
            model_name='compuesta',
            name='id_rutina',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='routine_app.rutina'),
        ),
        migrations.AddField(
            model_name='seasigna',
            name='id_cliente',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='routine_app.cliente'),
        ),
        migrations.AddField(
            model_name='seasigna',
            name='id_ejercicio',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='routine_app.ejercicio'),
        ),
        migrations.AddField(
            model_name='seasigna',
            name='id_rutina',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='routine_app.rutina'),
        ),
        migrations.AddConstraint(
            model_name='compuesta',
            constraint=models.UniqueConstraint(fields=('id_rutina', 'id_ejercicio'), name='unique_compuesta_rutina_ejercicio'),
        ),
        migrations.AddConstraint(
            model_name='seasigna',
            constraint=models.UniqueConstraint(fields=('id_rutina', 'id_ejercicio', 'id_cliente', 'serie'), name='unique_seasigna_rutina_ejercicio_cliente_serie'),
        ),
    ]
