# Generated by Django 5.0.3 on 2025-01-14 06:33

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Alimento',
            fields=[
                ('id_alimento', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=150)),
                ('calorias', models.DecimalField(decimal_places=2, default=0.0, max_digits=7)),
                ('proteina_g', models.DecimalField(decimal_places=2, default=0.0, max_digits=6)),
                ('carbohidratos_g', models.DecimalField(decimal_places=2, default=0.0, max_digits=6)),
                ('grasa_g', models.DecimalField(decimal_places=2, default=0.0, max_digits=6)),
                ('api_id_referencia', models.CharField(max_length=10)),
                ('metrica_g', models.DecimalField(decimal_places=2, default=0.0, max_digits=5)),
                ('unidad_medida', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Ejercicio',
            fields=[
                ('id_ejercicio', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=200)),
                ('musculo', models.CharField(max_length=200)),
                ('equipamento', models.CharField(max_length=1000)),
                ('instrucciones', models.JSONField(max_length=1000)),
                ('imagen', models.URLField(blank=True, max_length=500, null=True)),
                ('objetivo', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Genero',
            fields=[
                ('id_genero', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Membresia',
            fields=[
                ('id_membresia', models.AutoField(primary_key=True, serialize=False)),
                ('duracion', models.CharField(max_length=15)),
            ],
        ),
        migrations.CreateModel(
            name='NivelActividad',
            fields=[
                ('id_nivel_actividad', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=30)),
                ('factor', models.DecimalField(decimal_places=2, default='0.00', max_digits=5)),
            ],
        ),
        migrations.CreateModel(
            name='NivelGym',
            fields=[
                ('id_nivel_gym', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Objetivo',
            fields=[
                ('id_objetivo', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='ParteDia',
            fields=[
                ('id_parte_dia', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=30)),
                ('icono', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Administrador',
            fields=[
                ('id_administrador', models.AutoField(primary_key=True, serialize=False)),
                ('borrado', models.BooleanField(default=False)),
                ('nombre', models.CharField(max_length=50)),
                ('apellido', models.CharField(max_length=50)),
                ('cedula', models.CharField(max_length=10)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id_cliente', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=50)),
                ('apellido', models.CharField(max_length=50)),
                ('cedula', models.CharField(max_length=10)),
                ('tmb', models.DecimalField(decimal_places=2, default=0.0, max_digits=7)),
                ('altura', models.DecimalField(decimal_places=2, default=0.0, max_digits=5)),
                ('peso', models.DecimalField(decimal_places=2, default=0.0, max_digits=5)),
                ('fecha_nacimiento', models.DateField()),
                ('carbohidratos_g', models.DecimalField(decimal_places=2, default=0.0, max_digits=7)),
                ('proteina_g', models.DecimalField(decimal_places=2, default=0.0, max_digits=7)),
                ('grasas_g', models.DecimalField(decimal_places=2, default=0.0, max_digits=7)),
                ('borrado', models.BooleanField(default=False)),
                ('fecha_inicio', models.DateField()),
                ('fecha_fin', models.DateField()),
                ('imagen', models.ImageField(default='client_images/default.png', upload_to='trainer_images/')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Consume',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField(auto_now_add=True)),
                ('id_alimento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='routine_app.alimento')),
                ('id_cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='routine_app.cliente')),
            ],
        ),
        migrations.CreateModel(
            name='Entrenador',
            fields=[
                ('id_entrenador', models.AutoField(primary_key=True, serialize=False)),
                ('borrado', models.BooleanField(default=False)),
                ('nombre', models.CharField(max_length=50)),
                ('apellido', models.CharField(max_length=50)),
                ('cedula', models.CharField(max_length=10)),
                ('imagen', models.ImageField(default='trainer_images/default.jpg', upload_to='trainer_images/')),
                ('id_administrador', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='routine_app.administrador')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='cliente',
            name='id_entrenador',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='routine_app.entrenador'),
        ),
        migrations.AddField(
            model_name='cliente',
            name='id_genero',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='routine_app.genero'),
        ),
        migrations.AddField(
            model_name='cliente',
            name='id_membresia',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='routine_app.membresia'),
        ),
        migrations.AddField(
            model_name='cliente',
            name='id_nivel_actividad',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='routine_app.nivelactividad'),
        ),
        migrations.AddField(
            model_name='cliente',
            name='id_nivel_gym',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='routine_app.nivelgym'),
        ),
        migrations.AddField(
            model_name='cliente',
            name='id_objetivo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='routine_app.objetivo'),
        ),
        migrations.CreateModel(
            name='Dispone',
            fields=[
                ('id_dispone', models.AutoField(primary_key=True, serialize=False)),
                ('fecha', models.DateField(auto_now_add=True)),
                ('cantidad', models.DecimalField(decimal_places=2, default=0.0, max_digits=5)),
                ('tamaño_porcion_g', models.CharField(max_length=50)),
                ('gramos', models.DecimalField(decimal_places=2, default=0.0, max_digits=5)),
                ('id_alimento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='alimento_dispone', to='routine_app.alimento')),
                ('id_cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cliente_dispone', to='routine_app.cliente')),
                ('id_parte_dia', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='routine_app.partedia')),
            ],
        ),
        migrations.CreateModel(
            name='Rutina',
            fields=[
                ('id_rutina', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=50)),
                ('descripcion', models.CharField(max_length=200)),
                ('enfoque', models.CharField(max_length=50)),
                ('tipo', models.CharField(max_length=20)),
                ('id_entrenador', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='routine_app.entrenador')),
            ],
        ),
        migrations.CreateModel(
            name='Compuesta',
            fields=[
                ('id_compuesta', models.AutoField(primary_key=True, serialize=False)),
                ('id_ejercicio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='routine_app.ejercicio')),
                ('id_rutina', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='routine_app.rutina')),
            ],
        ),
        migrations.CreateModel(
            name='SeAsigna',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notas', models.CharField(blank=True, max_length=200, null=True)),
                ('tiempo_descanso', models.IntegerField(blank=True, help_text='Tiempo estimado en minutos', null=True)),
                ('serie', models.IntegerField()),
                ('repeticiones', models.IntegerField()),
                ('peso', models.IntegerField()),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('dia', models.CharField(max_length=30)),
                ('tipo', models.CharField(max_length=30)),
                ('asignado', models.CharField(blank=True, max_length=50, null=True)),
                ('id_cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='routine_app.cliente')),
                ('id_ejercicio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='routine_app.ejercicio')),
                ('id_rutina', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='routine_app.rutina')),
            ],
        ),
        migrations.AddConstraint(
            model_name='consume',
            constraint=models.UniqueConstraint(fields=('id_cliente', 'id_alimento'), name='unique_cliente_alimento'),
        ),
        migrations.AddConstraint(
            model_name='compuesta',
            constraint=models.UniqueConstraint(fields=('id_rutina', 'id_ejercicio'), name='unique_compuesta_rutina_ejercicio'),
        ),
    ]
