# Generated by Django 5.0.3 on 2024-11-29 15:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('routine_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='seasigna',
            name='tipo',
            field=models.CharField(default='', max_length=30),
            preserve_default=False,
        ),
    ]
