# Generated by Django 5.0.3 on 2024-03-11 20:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('routine_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='alimento',
            name='calorias',
            field=models.DecimalField(decimal_places=2, max_digits=5),
        ),
    ]
