# Generated by Django 5.0.3 on 2024-11-29 21:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('routine_app', '0002_seasigna_tipo'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='seasigna',
            name='unique_seasigna_rutina_ejercicio_cliente_serie',
        ),
    ]
