# Generated by Django 5.0.3 on 2024-11-30 17:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('routine_app', '0003_remove_seasigna_unique_seasigna_rutina_ejercicio_cliente_serie'),
    ]

    operations = [
        migrations.AddField(
            model_name='seasigna',
            name='asignado',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
