# Generated by Django 5.0.3 on 2025-01-16 04:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('routine_app', '0003_populate_exercises'),
    ]

    operations = [
        migrations.AlterField(
            model_name='alimento',
            name='unidad_medida',
            field=models.CharField(default='g', max_length=20),
            preserve_default=False,
        ),
    ]
