# Generated by Django 5.0.3 on 2024-11-30 17:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('routine_app', '0004_seasigna_asignado'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='seasigna',
            name='asignado',
        ),
    ]
