# Generated by Django 5.0.3 on 2025-01-24 18:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('routine_app', '0005_alimento_unidad_medida'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='administrador',
            name='borrado',
        ),
        migrations.AlterField(
            model_name='seasigna',
            name='tiempo_descanso',
            field=models.IntegerField(default=0, help_text='Tiempo estimado en minutos'),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='AdminLoginLog',
            fields=[
                ('id_log', models.AutoField(primary_key=True, serialize=False)),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('tiempo_tarea', models.FloatField()),
                ('id_administrador', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='routine_app.administrador')),
            ],
        ),
    ]
