# Generated by Django 5.0.3 on 2024-11-30 20:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('routine_app', '0005_remove_seasigna_asignado'),
    ]

    operations = [
        migrations.AddField(
            model_name='seasigna',
            name='asignado',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
