# Generated by Django 5.0.3 on 2024-12-01 01:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('routine_app', '0006_seasigna_asignado'),
    ]

    operations = [
        migrations.AlterField(
            model_name='seasigna',
            name='fecha',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
