# Generated by Django 5.0.3 on 2025-01-24 18:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('routine_app', '0006_remove_administrador_borrado_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tarea',
            fields=[
                ('id_tarea', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='TiempoTarea',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('tiempo_tarea', models.FloatField()),
                ('id_administrador', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='routine_app.administrador')),
                ('id_tarea', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='routine_app.tarea')),
            ],
        ),
        migrations.DeleteModel(
            name='AdminLoginLog',
        ),
    ]
