# Generated by Django 4.2.7 on 2024-03-13 01:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('routine_app', '0006_llenar_objetivos'),
    ]

    operations = [
        migrations.AddField(
            model_name='cliente',
            name='altura',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='cliente',
            name='peso',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5),
            preserve_default=False,
        ),
    ]
