# Generated by Django 4.2.7 on 2024-03-13 02:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('routine_app', '0007_cliente_altura_cliente_peso'),
    ]

    operations = [
        migrations.AddField(
            model_name='nivelactividad',
            name='factor',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5),
            preserve_default=False,
        ),
    ]
