# Generated by Django 5.0.3 on 2024-12-14 03:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('routine_app', '0007_alter_seasigna_fecha'),
    ]

    operations = [
        migrations.CreateModel(
            name='Membresia',
            fields=[
                ('id_membresia', models.AutoField(primary_key=True, serialize=False)),
                ('duracion', models.CharField(max_length=15)),
            ],
        ),
    ]
