# Generated by Django 5.0.3 on 2025-01-24 18:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('routine_app', '0007_tarea_tiempotarea_delete_adminloginlog'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tiempotarea',
            name='id_administrador',
        ),
        migrations.AddField(
            model_name='tiempotarea',
            name='content_type',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='tiempotarea',
            name='object_id',
            field=models.PositiveIntegerField(default=1),
            preserve_default=False,
        ),
    ]
