# Generated by Django 4.2.7 on 2024-03-12 23:39

from django.db import migrations

def crear_niveles_actividad(apps,schema_editor):
    NivelActividad = apps.get_model('routine_app', 'nivelActividad')
    nombres_y_factores = [
        ('Sedentario', 1.2),
        ('Ligeramente activo', 1.375),
        ('Moderadamente activo', 1.55),
        ('Muy activo', 1.725),
        ('Extra activo', 1.9),
    ]
    for nombre, factor in nombres_y_factores:
        nivel = NivelActividad.objects.filter(nombre=nombre).first()
        if nivel:
            nivel.factor = factor
            nivel.save()

def revertir_creacion_niveles(apps,schema_editor):
    NivelActividad = apps.get_model('routine_app','nivelActividad')
    nombres = ['Sedentario', 'Ligeramente activo', 'Moderadamente activo', 'Muy activo', 'Extra activo']
    NivelActividad.objects.filter(nombre__in=nombres).delete() #La eliminación solo considera el nombre

class Migration(migrations.Migration):

    dependencies = [
        ('routine_app', '0008_nivelactividad_factor'),
    ]

    operations = [
        migrations.RunPython(crear_niveles_actividad, revertir_creacion_niveles)
    ]
