# Generated by Django 5.0.3 on 2024-12-14 04:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('routine_app', '0008_membresia'),
    ]

    operations = [
        migrations.AddField(
            model_name='cliente',
            name='id_membresia',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE, to='routine_app.membresia'),
            preserve_default=False,
        ),
    ]
