# Generated by Django 5.0.3 on 2025-01-24 21:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('routine_app', '0008_remove_tiempotarea_id_administrador_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='tiempotarea',
            name='tipoUsuario',
            field=models.CharField(default=0, max_length=50),
            preserve_default=False,
        ),
    ]
