# Generated by Django 5.0.3 on 2025-05-22 02:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('routine_app', '0009_tiempotarea_tipousuario'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tiempotarea',
            name='id_tarea',
        ),
        migrations.RemoveField(
            model_name='tiempotarea',
            name='content_type',
        ),
        migrations.AlterField(
            model_name='seasigna',
            name='tiempo_descanso',
            field=models.IntegerField(blank=True, help_text='Tiempo estimado en minutos', null=True),
        ),
        migrations.DeleteModel(
            name='Tarea',
        ),
        migrations.DeleteModel(
            name='TiempoTarea',
        ),
    ]
