# Generated by Django 5.0.3 on 2024-12-14 05:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('routine_app', '0009_cliente_id_membresia'),
    ]

    operations = [
        migrations.AddField(
            model_name='cliente',
            name='fecha_fin',
            field=models.DateField(default='2025-01-14'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='cliente',
            name='fecha_inicio',
            field=models.DateField(default='2024-12-14'),
            preserve_default=False,
        ),
    ]
