# Generated by Django 5.0.3 on 2024-03-16 03:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('routine_app', '0010_cliente_tmb'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cliente',
            name='tmb',
            field=models.DecimalField(decimal_places=2, max_digits=7),
        ),
    ]
