# Generated by Django 5.0.3 on 2024-12-17 04:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('routine_app', '0010_cliente_fecha_fin_cliente_fecha_inicio'),
    ]

    operations = [
        migrations.AddField(
            model_name='seasigna',
            name='notas',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='seasigna',
            name='tiempo',
            field=models.IntegerField(blank=True, help_text='Tiempo estimado en minutos', null=True),
        ),
    ]
