# Generated by Django 5.0.3 on 2024-12-17 05:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('routine_app', '0011_seasigna_notas_seasigna_tiempo'),
    ]

    operations = [
        migrations.RenameField(
            model_name='seasigna',
            old_name='tiempo',
            new_name='tiempo_descanso',
        ),
        migrations.AddField(
            model_name='seasigna',
            name='tiempo_rutina',
            field=models.IntegerField(blank=True, help_text='Tiempo estimado en minutos', null=True),
        ),
    ]
