# Generated by Django 5.0.3 on 2024-12-17 05:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('routine_app', '0012_rename_tiempo_seasigna_tiempo_descanso_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='seasigna',
            name='tiempo_rutina',
        ),
    ]
