# Generated by Django 5.0.3 on 2024-03-16 19:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('routine_app', '0012_cliente_carbohidratos_g_cliente_grasas_g_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cliente',
            name='carbohidratos_g',
            field=models.DecimalField(decimal_places=2, max_digits=7),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='grasas_g',
            field=models.DecimalField(decimal_places=2, max_digits=7),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='proteina_g',
            field=models.DecimalField(decimal_places=2, max_digits=7),
        ),
    ]
