# Generated by Django 5.0.3 on 2024-12-26 03:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('routine_app', '0013_remove_seasigna_tiempo_rutina'),
    ]

    operations = [
        migrations.AddField(
            model_name='cliente',
            name='imagen',
            field=models.ImageField(blank=True, null=True, upload_to='entrenador_images/'),
        ),
        migrations.AddField(
            model_name='entrenador',
            name='imagen',
            field=models.ImageField(blank=True, null=True, upload_to='entrenador_images/'),
        ),
    ]
