# Generated by Django 5.0.3 on 2024-03-16 20:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('routine_app', '0013_alter_cliente_carbohidratos_g_alter_cliente_grasas_g_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cliente',
            name='tmb',
        ),
    ]
