# Generated by Django 5.0.3 on 2024-12-27 18:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('routine_app', '0014_cliente_imagen_entrenador_imagen'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entrenador',
            name='imagen',
            field=models.ImageField(default='trainer_images/default.jpg', upload_to='trainer_images/'),
        ),
    ]
