# Generated by Django 5.0.3 on 2024-03-16 20:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('routine_app', '0014_remove_cliente_tmb'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cliente',
            name='carbohidratos_g',
        ),
        migrations.RemoveField(
            model_name='cliente',
            name='grasas_g',
        ),
        migrations.RemoveField(
            model_name='cliente',
            name='proteina_g',
        ),
    ]
