# Generated by Django 5.0.3 on 2024-12-29 04:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('routine_app', '0015_alter_entrenador_imagen'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cliente',
            name='imagen',
            field=models.ImageField(default='client_images/default.png', upload_to='trainer_images/'),
        ),
    ]
