# Generated by Django 5.0.3 on 2024-03-16 20:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('routine_app', '0015_remove_cliente_carbohidratos_g_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='cliente',
            name='tmb',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=7),
            preserve_default=False,
        ),
    ]
