# Generated by Django 5.0.3 on 2024-03-16 20:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('routine_app', '0016_cliente_tmb'),
    ]

    operations = [
        migrations.AddField(
            model_name='cliente',
            name='carbohidratos_g',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=7),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='cliente',
            name='grasas_g',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=7),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='cliente',
            name='proteina_g',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=7),
            preserve_default=False,
        ),
    ]
