# Generated by Django 5.0.3 on 2024-12-31 17:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('routine_app', '0016_alter_cliente_imagen'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dispone',
            name='cantidad',
            field=models.DecimalField(decimal_places=2, max_digits=5),
        ),
    ]
