# Generated by Django 5.0.3 on 2024-12-31 17:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('routine_app', '0017_alter_dispone_cantidad'),
    ]

    operations = [
        migrations.AddField(
            model_name='dispone',
            name='gramos',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5),
            preserve_default=False,
        ),
    ]
