# Generated by Django 5.0.3 on 2024-03-20 03:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('routine_app', '0018_remove_administrador_apellido_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CustomUser',
        ),
    ]
