# Generated by Django 5.0.3 on 2025-01-02 02:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('routine_app', '0018_dispone_gramos'),
    ]

    operations = [
        migrations.AddField(
            model_name='dispone',
            name='metrica_g',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5),
            preserve_default=False,
        ),
    ]
