# Generated by Django 5.0.3 on 2024-03-20 04:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('routine_app', '0019_delete_customuser'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='administrador',
            name='user',
        ),
        migrations.RemoveField(
            model_name='entrenador',
            name='user',
        ),
    ]
