# Generated by Django 5.0.3 on 2025-01-02 02:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('routine_app', '0019_dispone_metrica_g'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dispone',
            name='metrica_g',
        ),
        migrations.AddField(
            model_name='alimento',
            name='metrica_g',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5),
            preserve_default=False,
        ),
    ]
