# Generated by Django 5.0.3 on 2025-01-02 16:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('routine_app', '0020_remove_dispone_metrica_g_alimento_metrica_g'),
    ]

    operations = [
        migrations.AddField(
            model_name='alimento',
            name='unidad_medida',
            field=models.CharField(decimal_places=2, default="", max_digits=5),
            preserve_default=False,
        ),
    ]
