# Generated by Django 5.0.3 on 2025-01-02 16:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('routine_app', '0021_alimento_unidad_medida'),
    ]

    operations = [
        migrations.AlterField(
            model_name='alimento',
            name='unidad_medida',
            field=models.CharField(max_length=20),
        ),
    ]
