# Generated by Django 5.0.3 on 2025-01-14 06:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('routine_app', '0022_alter_alimento_unidad_medida'),
    ]

    operations = [
        migrations.AlterField(
            model_name='alimento',
            name='calorias',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=7),
        ),
        migrations.AlterField(
            model_name='alimento',
            name='carbohidratos_g',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=6),
        ),
        migrations.AlterField(
            model_name='alimento',
            name='grasa_g',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=6),
        ),
        migrations.AlterField(
            model_name='alimento',
            name='metrica_g',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=5),
        ),
        migrations.AlterField(
            model_name='alimento',
            name='proteina_g',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=6),
        ),
        migrations.AlterField(
            model_name='dispone',
            name='cantidad',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=5),
        ),
        migrations.AlterField(
            model_name='dispone',
            name='gramos',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=5),
        ),
        migrations.AlterField(
            model_name='nivelactividad',
            name='factor',
            field=models.DecimalField(decimal_places=2, default='0.00', max_digits=5),
        ),
    ]
