# Generated by Django 5.0.3 on 2024-03-21 03:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('routine_app', '0023_alter_cliente_altura_alter_cliente_carbohidratos_g_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='entrenador',
            name='email',
        ),
    ]
