# Generated by Django 5.0.3 on 2024-03-22 02:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('routine_app', '0024_remove_entrenador_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='administrador',
            name='borrado',
            field=models.CharField(default=False),
        ),
        migrations.AddField(
            model_name='cliente',
            name='borrado',
            field=models.CharField(default=False),
        ),
        migrations.AddField(
            model_name='entrenador',
            name='borrado',
            field=models.CharField(default=False),
        ),
    ]
