# Generated by Django 5.0.3 on 2024-03-24 00:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('routine_app', '0025_administrador_borrado_cliente_borrado_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ejercicio',
            fields=[
                ('id_ejercicio', models.CharField(primary_key=True, serialize=False)),
                ('equipamento', models.CharField(max_length=100)),
                ('instrucciones', models.CharField(max_length=100)),
                ('nombre', models.CharField(max_length=50)),
                ('tipo', models.CharField(max_length=50)),
                ('parte_cuerpo', models.CharField(max_length=100)),
                ('musculo', models.CharField(max_length=100)),
                ('imagen', models.ImageField(blank=True, null=True, upload_to='ejercicios')),
            ],
        ),
        migrations.RemoveField(
            model_name='cliente',
            name='edad',
        ),
        migrations.CreateModel(
            name='Rutina',
            fields=[
                ('id_rutina', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=50)),
                ('descripcion', models.CharField(max_length=200)),
                ('tipo', models.CharField(max_length=20)),
                ('id_entrenador', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='routine_app.entrenador')),
            ],
        ),
    ]
