# Generated by Django 5.0.3 on 2024-03-24 01:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('routine_app', '0026_ejercicio_remove_cliente_edad_rutina'),
    ]

    operations = [
        migrations.AddField(
            model_name='cliente',
            name='fecha_nacimiento',
            field=models.DateField(default='1990-01-01'),
            preserve_default=False,
        ),
    ]
