# Generated by Django 5.0.3 on 2024-03-26 22:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('routine_app', '0027_cliente_fecha_nacimiento'),
    ]

    operations = [
        migrations.CreateModel(
            name='Compuesta',
            fields=[
                ('series', models.AutoField(primary_key=True, serialize=False)),
                ('repeticiones', models.IntegerField()),
                ('peso', models.IntegerField()),
                ('fecha', models.DateField(auto_now_add=True)),
                ('tipo', models.CharField(max_length=50)),
                ('id_cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='routine_app.cliente')),
                ('id_ejercicio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='routine_app.ejercicio')),
                ('id_rutina', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='routine_app.rutina')),
            ],
        ),
    ]
