# Generated by Django 5.0.3 on 2024-03-27 03:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('routine_app', '0027_cliente_fecha_nacimiento'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ejercicio',
            name='parte_cuerpo',
        ),
        migrations.RemoveField(
            model_name='ejercicio',
            name='tipo',
        ),
        migrations.AddField(
            model_name='ejercicio',
            name='objetivo',
            field=models.CharField(default=0, max_length=20),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='ejercicio',
            name='id_ejercicio',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='ejercicio',
            name='instrucciones',
            field=models.JSONField(max_length=100),
        ),
        migrations.AlterField(
            model_name='ejercicio',
            name='musculo',
            field=models.CharField(max_length=50),
        ),
    ]
