# Generated by Django 5.0.3 on 2024-03-27 18:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('routine_app', '0029_remove_ejercicio_parte_cuerpo_remove_ejercicio_tipo_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ejercicio',
            name='equipamento',
            field=models.CharField(max_length=1000),
        ),
        migrations.AlterField(
            model_name='ejercicio',
            name='instrucciones',
            field=models.JSONField(max_length=1000),
        ),
         migrations.AlterField(
            model_name='ejercicio',
            name='objetivo',
            field=models.CharField(max_length=100),
        ),
    ]
