# Generated by Django 5.0.3 on 2024-03-26 22:19

from django.db import migrations
import requests

# Mapeos de traducción

# Mapeos de traducción extendidos para incluir nombres de ejercicios
traducciones_nombres_ejercicios = {
    "alternate lateral pulldown": "pulldown lateral alternativo",
    "archer pull up": "dominada de arquero",
    "assisted parallel close grip pull-up": "dominada asistida con agarre cerrado y paralelo",
    "assisted pull-up": "dominada asistida",
    "assisted standing chin-up": "chin-up asistido de pie",
    "assisted standing pull-up": "pull-up asistido de pie",
    "back extension on exercise ball": "extensión de espalda en balón de ejercicio",
    "back lever": "palanca trasera",
    "back pec stretch": "estiramiento de pectorales y espalda",
    "band assisted pull-up": "pull-up asistido con banda",
}

traducciones_parte_del_cuerpo = {
    "back": "espalda",
}

traducciones_equipo = {
    "cable": "cable",
    "body weight": "peso corporal",
    "leverage machine": "máquina de palanca",
    "stability ball": "balón de estabilidad",
    "band": "banda",
}

traducciones_instrucciones = {
     # Instrucciones del ejercicio "alternate lateral pulldown"
    "Sit on the cable machine with your back straight and feet flat on the ground.": "Siéntate en la máquina de cable con la espalda recta y los pies planos en el suelo.",
    "Grasp the handles with an overhand grip, slightly wider than shoulder-width apart.": "Agarra las manijas con un agarre por encima de la mano, ligeramente más ancho que el ancho de los hombros.",
    "Lean back slightly and pull the handles towards your chest, squeezing your shoulder blades together.": "Inclínate ligeramente hacia atrás y tira de las manijas hacia tu pecho, apretando las escápulas.",
    "Pause for a moment at the peak of the movement, then slowly release the handles back to the starting position.": "Haz una pausa por un momento en el punto máximo del movimiento, luego suelta lentamente las manijas de vuelta a la posición inicial.",
    "Repeat for the desired number of repetitions.": "Repite el número deseado de repeticiones.",
    "Start by hanging from a pull-up bar with an overhand grip, slightly wider than shoulder-width apart.": "Comienza colgándote de una barra de dominadas con un agarre por encima de la mano, ligeramente más ancho que el ancho de los hombros.",
    # Instrucciones del ejercicio "alternate lateral pulldown"
    "Start by hanging from a pull-up bar with an overhand grip, slightly wider than shoulder-width apart.": "Comienza colgándote de una barra de dominadas con un agarre por encima, un poco más ancho que el ancho de los hombros.",
    "Engage your core and pull your shoulder blades down and back.": "Activa tu núcleo y jala tus omóplatos hacia abajo y hacia atrás.",
    "As you pull yourself up, bend one arm and bring your elbow towards your side, while keeping the other arm straight.": "Mientras te jalas hacia arriba, dobla un brazo y acerca el codo a tu costado, mientras mantienes el otro brazo recto.",
    "Continue pulling until your chin is above the bar and your bent arm is fully flexed.": "Continúa jalando hasta que tu barbilla esté por encima de la barra y tu brazo doblado esté completamente flexionado.",
    "Lower yourself back down with control, straightening the bent arm and repeating the movement on the other side.": "Bájate con control, enderezando el brazo doblado y repitiendo el movimiento en el otro lado.",
    "Alternate sides with each repetition.": "Alterna lados con cada repetición.",
    # Instrucciones del ejercicio "assisted parallel close grip pull-up"
    "Adjust the machine to your desired weight and height.": "Ajusta la máquina a tu peso y altura deseados.",
    "Place your hands on the parallel bars with a close grip, palms facing each other.": "Coloca tus manos en las barras paralelas con un agarre cerrado, las palmas enfrentadas entre sí.",
    "Hang from the bars with your arms fully extended and your feet off the ground.": "Cuelga de las barras con tus brazos completamente extendidos y tus pies fuera del suelo.",
    "Engage your back muscles and pull your body up towards the bars, keeping your elbows close to your body.": "Activa los músculos de tu espalda y jala tu cuerpo hacia las barras, manteniendo los codos cerca de tu cuerpo.",
    "Continue pulling until your chin is above the bars.": "Continúa jalando hasta que tu barbilla esté por encima de las barras.",
    "Pause for a moment at the top, then slowly lower your body back down to the starting position.": "Haz una pausa un momento en la parte superior, luego baja lentamente tu cuerpo de vuelta a la posición inicial.",
    "Repeat for the desired number of repetitions.": "Repite el número deseado de repeticiones.",
    # Instrucciones del ejercicio "assisted pull-up"
    "Adjust the machine to your desired weight and height settings.": "Ajusta la máquina a los ajustes de peso y altura deseados.",
    "Grasp the handles with an overhand grip, slightly wider than shoulder-width apart.": "Agarra las manijas con un agarre por encima de la mano, un poco más ancho que el ancho de los hombros.",
    "Hang with your arms fully extended and your feet off the ground.": "Cuelga con tus brazos completamente extendidos y tus pies fuera del suelo.",
    "Engage your back muscles and pull your body up towards the handles, keeping your elbows close to your body.": "Activa los músculos de tu espalda y eleva tu cuerpo hacia las manijas, manteniendo los codos cerca de tu cuerpo.",
    "Continue pulling until your chin is above the handles.": "Continúa jalando hasta que tu barbilla esté por encima de las manijas.",
    "Pause for a moment at the top, then slowly lower your body back down to the starting position.": "Haz una pausa por un momento en la parte superior, luego baja lentamente tu cuerpo de vuelta a la posición inicial.",
    "Repeat for the desired number of repetitions.": "Repite para el número deseado de repeticiones.",
     # Instrucciones del ejercicio "assisted standing chin-up"
     "Adjust the machine to your desired assistance level.": "Ajusta la máquina al nivel de asistencia deseado.",
    "Stand on the foot platform and grip the handles with an overhand grip, slightly wider than shoulder-width apart.": "Párate en la plataforma para los pies y agarra las manijas con un agarre por encima, ligeramente más ancho que el ancho de los hombros.",
    "Keep your chest up and shoulders back, engage your core, and slightly bend your knees.": "Mantén tu pecho hacia arriba y los hombros hacia atrás, activa tu núcleo y dobla ligeramente las rodillas.",
    "Pull your body up by flexing your elbows and driving your elbows down towards your sides.": "Eleva tu cuerpo flexionando los codos y llevándolos hacia abajo a tus costados.",
    "Continue pulling until your chin is above the bar.": "Continúa jalando hasta que tu barbilla esté por encima de la barra.",
    "Pause for a moment at the top, then slowly lower your body back down to the starting position.": "Haz una pausa por un momento en la cima, luego baja lentamente tu cuerpo a la posición inicial.",
    "Repeat for the desired number of repetitions.": "Repite para el número deseado de repeticiones.",
    # Instrucciones del ejercicio "assisted standing pull-up"
     "Adjust the machine to your desired weight and height settings.": "Ajusta la máquina a los ajustes de peso y altura deseados.",
    "Stand facing the machine with your feet shoulder-width apart.": "Párate frente a la máquina con los pies separados al ancho de los hombros.",
    "Grasp the handles with an overhand grip, slightly wider than shoulder-width apart.": "Agarra las manijas con un agarre por encima, ligeramente más ancho que el ancho de los hombros.",
    "Engage your lats and biceps, and pull yourself up towards the handles.": "Activa tus dorsales y bíceps, y jálate hacia arriba hacia las manijas.",
    "Pause for a moment at the top, squeezing your back muscles.": "Haz una pausa por un momento en la cima, apretando tus músculos de la espalda.",
    "Slowly lower yourself back down to the starting position.": "Baja lentamente a la posición inicial.",
    "Repeat for the desired number of repetitions.": "Repite para el número deseado de repeticiones.",
    # Instrucciones del ejercicio "back extension on exercise ball"
    "Place the stability ball on the ground and lie face down on top of it, with your hips resting on the ball and your feet against a wall or other stable surface.": "Coloca el balón de estabilidad en el suelo y túmbate boca abajo sobre él, con las caderas apoyadas en el balón y los pies contra una pared u otra superficie estable.",
    "Position your hands behind your head or crossed over your chest.": "Posiciona tus manos detrás de tu cabeza o cruzadas sobre tu pecho.",
    "Engage your core and slowly lift your upper body off the ball, extending your back until your body forms a straight line from your head to your heels.": "Activa tu núcleo y levanta lentamente tu torso del balón, extendiendo tu espalda hasta que tu cuerpo forme una línea recta desde tu cabeza hasta tus talones.",
    "Pause for a moment at the top, then slowly lower your upper body back down to the starting position.": "Haz una pausa por un momento en la parte superior, luego baja lentamente tu torso a la posición inicial.",
    "Repeat for the desired number of repetitions.": "Repite para el número deseado de repeticiones.",
    # Instrucciones del ejercicio "back lever"
    "Start by hanging from a pull-up bar with an overhand grip, hands slightly wider than shoulder-width apart.": "Comienza colgándote de una barra de dominadas con un agarre por encima, manos ligeramente más anchas que el ancho de los hombros.",
    "Engage your core and pull your shoulder blades down and back.": "Activa tu núcleo y jala tus omóplatos hacia abajo y hacia atrás.",
    "Bend your knees and tuck them towards your chest.": "Dobla tus rodillas y acércalas hacia tu pecho.",
    "Slowly lift your legs up, keeping them straight, until your body is parallel to the ground.": "Levanta lentamente tus piernas, manteniéndolas rectas, hasta que tu cuerpo esté paralelo al suelo.",
    "Hold this position for a few seconds, then slowly lower your legs back down to the starting position.": "Mantén esta posición durante unos segundos, luego baja lentamente tus piernas de vuelta a la posición inicial.",
    "Repeat for the desired number of repetitions.": "Repite para el número deseado de repeticiones.",
    # Instrucciones del ejercicio "back pec stretch"
    "Stand tall with your feet shoulder-width apart.": "Ponte de pie, alto, con los pies separados al ancho de los hombros.",
    "Extend your arms straight out in front of you, parallel to the ground.": "Extiende tus brazos rectos frente a ti, paralelos al suelo.",
    "Cross your arms in front of your body, with your right arm over your left arm.": "Cruza tus brazos frente a tu cuerpo, con el brazo derecho sobre el izquierdo.",
    "Interlock your fingers and rotate your palms away from your body.": "Entrelaza tus dedos y rota tus palmas alejándolas de tu cuerpo.",
    "Slowly raise your arms up and away from your body, feeling a stretch in your back and chest.": "Levanta lentamente tus brazos hacia arriba y alejándolos de tu cuerpo, sintiendo un estiramiento en tu espalda y pecho.",
    "Hold the stretch for 15-30 seconds, then release.": "Mantén el estiramiento durante 15-30 segundos, luego suelta.",
    "Repeat on the opposite side.": "Repite en el lado opuesto.",
    # Instrucciones del ejercicio "band assisted pull-up"
    "Attach the band to a pull-up bar or sturdy anchor point.": "Adjunta la banda a una barra de dominadas o un punto de anclaje resistente.",
    "Step onto the band and grip the bar with your palms facing away from you, hands slightly wider than shoulder-width apart.": "Pisa la banda y agarra la barra con las palmas hacia afuera, las manos ligeramente más anchas que el ancho de los hombros.",
    "Hang with your arms fully extended, keeping your core engaged and your shoulders down and back.": "Cuelga con los brazos completamente extendidos, manteniendo el núcleo activado y los hombros hacia abajo y hacia atrás.",
    "Pull your body up towards the bar by squeezing your shoulder blades together and driving your elbows down towards your hips.": "Jala tu cuerpo hacia la barra apretando tus omóplatos y llevando tus codos hacia tus caderas.",
    "Continue pulling until your chin is above the bar, then slowly lower yourself back down to the starting position.": "Continúa jalando hasta que tu barbilla esté por encima de la barra, luego baja lentamente a la posición inicial.",
    "Repeat for the desired number of repetitions.": "Repite para el número deseado de repeticiones."
}


traducciones_objetivo = {
    "lats": "dorsales",
    "spine": "columna",
    "upper back": "parte superior de la espalda",
}


def llenar_catalogo(apps,schema_editor):
    Ejercicio = apps.get_model('routine_app','Ejercicio')   

    url = "https://exercisedb.p.rapidapi.com/exercises/bodyPart/back"
    querystring = {"limit":"10"}
    headers = {
        'X-RapidAPI-Key': '891b93fa0emsh072b1fbe8965257p128f0ajsn2fee5da1207b',
        'X-RapidAPI-Host': 'exercisedb.p.rapidapi.com'
    }

    response = requests.request("GET", url, headers=headers, params=querystring)

    if response.status_code == 200:
        data = response.json()
        for ejercicio in data:  
            instrucciones_traducidas = [traducciones_instrucciones[inst] for inst in ejercicio['instructions']]
            nuevo_ejercicio = Ejercicio(
                nombre=traducciones_nombres_ejercicios[ejercicio['name']],
                musculo=traducciones_parte_del_cuerpo[ejercicio['bodyPart']],
                equipamento=traducciones_equipo[ejercicio['equipment']],
                instrucciones=" ".join(instrucciones_traducidas),
                imagen=ejercicio['gifUrl'],
                objetivo=traducciones_objetivo[ejercicio['target']]
            )
            nuevo_ejercicio.save()


def revertir_llenar_catalogo(apps,schema_editor):
    Ejercicio = apps.get_model('routine_app','Ejercicio')
    Ejercicio.objects.all().delete()


class Migration(migrations.Migration):

    dependencies = [
        ('routine_app', '0030_alter_ejercicio_equipamento_and_more'),
    ]

    operations = [
        migrations.RunPython(llenar_catalogo, revertir_llenar_catalogo)
    ]

