# Generated by Django 5.0.3 on 2024-03-27 19:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('routine_app', '0031_catalogo_ejercicios'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ejercicio',
            name='musculo',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='ejercicio',
            name='nombre',
            field=models.CharField(max_length=200),
        ),
    ]




