# Generated by Django 5.0.3 on 2024-03-26 22:19

from django.db import migrations
import requests


traducciones_nombres_ejercicios = {
    "archer push up": "flexión de arquero",
    "assisted chest dip (kneeling)": "fondo de pecho asistido (de rodillas)",
    "assisted seated pectoralis major stretch with stability ball": "estiramiento del pectoral mayor asistido sentado con balón de estabilidad",
    "assisted wide-grip chest dip (kneeling)": "fondo de pecho asistido con agarre amplio (de rodillas)",
    "band bench press": "press de banca con banda",
    "band one arm twisting chest press": "press de pecho con una mano y giro con banda",
    "barbell bench press": "press de banca con barra",
    "barbell decline bench press": "press de banca declinado con barra",
    "barbell decline pullover": "pullover declinado con barra",
    "barbell decline wide-grip press": "press declinado con agarre amplio con barra"
}


traducciones_parte_del_cuerpo = {
    "chest": "pecho",
}

traducciones_equipo = {
    "body weight": "peso corporal",
    "leverage machine": "máquina de palanca",
    "assisted": "asistido",
    "band": "banda",
    "barbell": "barra"
}


traducciones_instrucciones = {
    # Instrucciones del ejercicio "archer push up"
    "Start in a push-up position with your hands slightly wider than shoulder-width apart.": "Comienza en posición de flexión con las manos un poco más anchas que el ancho de los hombros.",
    "Extend one arm straight out to the side, parallel to the ground.": "Extiende un brazo recto hacia el lado, paralelo al suelo.",
    "Lower your body by bending your elbows, keeping your back straight and core engaged.": "Baja tu cuerpo doblando los codos, manteniendo la espalda recta y el núcleo activado.",
    "Push back up to the starting position.": "Empuja hacia arriba para volver a la posición inicial.",
    "Repeat on the other side, extending the opposite arm out to the side.": "Repite en el otro lado, extendiendo el brazo opuesto hacia el lado.",
    "Continue alternating sides for the desired number of repetitions.": "Continúa alternando lados para el número deseado de repeticiones.",
    # Instrucciones del ejercicio "assisted chest dip (kneeling)"
    "Adjust the machine to your desired height and secure your knees on the pad.": "Ajusta la máquina a la altura deseada y asegura tus rodillas en la almohadilla.",
    "Grasp the handles with your palms facing down and your arms fully extended.": "Agarra las manijas con las palmas hacia abajo y los brazos completamente extendidos.",
    "Lower your body by bending your elbows until your upper arms are parallel to the floor.": "Baja tu cuerpo doblando los codos hasta que tus brazos superiores estén paralelos al suelo.",
    "Pause for a moment, then push yourself back up to the starting position.": "Haz una pausa por un momento, luego empújate de nuevo a la posición inicial.",
    "Repeat for the desired number of repetitions.": "Repite para el número deseado de repeticiones.",
    # Instrucciones del ejercicio "assisted seated pectoralis major stretch with stability ball"
    "Sit on a stability ball with your feet flat on the ground and your back straight.": "Siéntate en un balón de estabilidad con los pies planos en el suelo y la espalda recta.",
    "Hold a stability ball with both hands and extend your arms straight out in front of you.": "Sostén un balón de estabilidad con ambas manos y extiende tus brazos rectos frente a ti.",
    "Slowly lower the stability ball towards your chest, feeling a stretch in your pectoral muscles.": "Baja lentamente el balón de estabilidad hacia tu pecho, sintiendo un estiramiento en tus músculos pectorales.",
    "Hold the stretch for a few seconds, then slowly return to the starting position.": "Mantén el estiramiento por unos segundos, luego regresa lentamente a la posición inicial.",
    "Repeat for the desired number of repetitions.": "Repite para el número deseado de repeticiones.",
    # Instrucciones del ejercicio "assisted wide-grip chest dip (kneeling)"
    "Adjust the machine to your desired height and secure your knees on the pad.": "Ajusta la máquina a tu altura deseada y asegura tus rodillas en la almohadilla.",
    "Grasp the handles with a wide grip and keep your elbows slightly bent.": "Agarra las manijas con un agarre amplio y mantén los codos ligeramente doblados.",
    "Lower your body by bending your elbows until your upper arms are parallel to the floor.": "Baja tu cuerpo doblando los codos hasta que tus brazos superiores estén paralelos al suelo.",
    "Push yourself back up to the starting position by extending your arms.": "Empújate de vuelta a la posición inicial extendiendo tus brazos.",
    "Repeat for the desired number of repetitions.": "Repite para el número deseado de repeticiones.",
    # Instrucciones del ejercicio "band bench press"
    "Lie flat on a bench with your feet flat on the ground and your back pressed against the bench.": "Acuéstate en un banco con los pies planos en el suelo y tu espalda presionada contra el banco.",
    "Grasp the band handles with an overhand grip, slightly wider than shoulder-width apart.": "Agarra las asas de la banda con un agarre por encima de la mano, ligeramente más ancho que el ancho de los hombros.",
    "Extend your arms fully, pushing the bands away from your chest.": "Extiende tus brazos completamente, empujando las bandas lejos de tu pecho.",
    "Slowly lower the bands back down to your chest, keeping your elbows at a 90-degree angle.": "Baja lentamente las bandas de vuelta a tu pecho, manteniendo tus codos en un ángulo de 90 grados.",
    "Repeat for the desired number of repetitions.": "Repite para el número deseado de repeticiones.",
    # Instrucciones del ejercicio "band one arm twisting chest press"
    "Attach the band to a sturdy anchor point at chest height.": "Adjunta la banda a un punto de anclaje resistente a la altura del pecho.",
    "Stand with your side facing the anchor point and grab the band with one hand.": "Párate con tu lado mirando hacia el punto de anclaje y agarra la banda con una mano.",
    "Step away from the anchor point to create tension in the band.": "Aléjate del punto de anclaje para crear tensión en la banda.",
    "Position your feet shoulder-width apart and slightly bend your knees.": "Posiciona tus pies a la anchura de los hombros y dobla ligeramente tus rodillas.",
    "Bring your hand holding the band across your body, towards the opposite shoulder.": "Lleva tu mano que sostiene la banda a través de tu cuerpo, hacia el hombro opuesto.",
    "While maintaining tension in the band, push your hand forward and away from your body, extending your arm.": "Mientras mantienes la tensión en la banda, empuja tu mano hacia adelante y lejos de tu cuerpo, extendiendo tu brazo.",
    "Slowly return to the starting position and repeat for the desired number of repetitions.": "Regresa lentamente a la posición inicial y repite para el número deseado de repeticiones.",
    "Switch sides and repeat the exercise with the other hand.": "Cambia de lado y repite el ejercicio con la otra mano.",
    # Instrucciones del ejercicio "barbell bench press"
    "Lie flat on a bench with your feet flat on the ground and your back pressed against the bench.": "Acuéstate en un banco con los pies planos en el suelo y tu espalda presionada contra el banco.",
    "Grasp the barbell with an overhand grip slightly wider than shoulder-width apart.": "Agarra la barra con un agarre por encima, ligeramente más ancho que el ancho de los hombros.",
    "Lift the barbell off the rack and hold it directly above your chest with your arms fully extended.": "Levanta la barra del soporte y mantenla directamente sobre tu pecho con los brazos completamente extendidos.",
    "Lower the barbell slowly towards your chest, keeping your elbows tucked in.": "Baja la barra lentamente hacia tu pecho, manteniendo los codos pegados al cuerpo.",
    "Pause for a moment when the barbell touches your chest.": "Haz una pausa por un momento cuando la barra toque tu pecho.",
    "Push the barbell back up to the starting position by extending your arms.": "Empuja la barra de vuelta a la posición inicial extendiendo tus brazos.",
    "Repeat for the desired number of repetitions.": "Repite para el número deseado de repeticiones.",
    # Instrucciones del ejercicio "barbell decline bench press"
    "Lie on a decline bench with your feet secured and your head lower than your hips.": "Acuéstate en un banco declinado con tus pies asegurados y tu cabeza más baja que tus caderas.",
    "Grasp the barbell with an overhand grip slightly wider than shoulder-width apart.": "Agarra la barra con un agarre por encima, ligeramente más ancho que el ancho de los hombros.",
    "Unrack the barbell and lower it slowly towards your chest, keeping your elbows tucked in.": "Desencaja la barra y bájala lentamente hacia tu pecho, manteniendo los codos pegados al cuerpo.",
    "Pause for a moment at the bottom, then push the barbell back up to the starting position.": "Haz una pausa por un momento en el punto más bajo, luego empuja la barra de vuelta a la posición inicial.",
    "Repeat for the desired number of repetitions.": "Repite para el número deseado de repeticiones.",
    # Instrucciones del ejercicio "barbell decline pullover"
    "Lie down on a decline bench with your head lower than your hips and your feet secured.": "Acuéstate en un banco declinado con tu cabeza más baja que tus caderas y tus pies asegurados.",
    "Hold the barbell with a pronated grip (palms facing away from you) and your hands slightly wider than shoulder-width apart.": "Sostén la barra con un agarre pronado (palmas hacia afuera) y tus manos ligeramente más anchas que el ancho de los hombros.",
    "Extend your arms above your chest, keeping a slight bend in your elbows.": "Extiende tus brazos sobre tu pecho, manteniendo un ligero doblez en tus codos.",
    "Lower the barbell in an arc motion behind your head, feeling a stretch in your chest and shoulders.": "Baja la barra en un movimiento de arco detrás de tu cabeza, sintiendo un estiramiento en tu pecho y hombros.",
    "Pause for a moment, then return the barbell to the starting position by reversing the motion.": "Haz una pausa por un momento, luego regresa la barra a la posición inicial invirtiendo el movimiento.",
    "Repeat for the desired number of repetitions.": "Repite para el número deseado de repeticiones.",
    # Instrucciones del ejercicio "barbell decline wide-grip press"
    "Lie on a decline bench with your feet secured and your head lower than your hips.": "Acuéstate en un banco declinado con tus pies asegurados y tu cabeza más baja que tus caderas.",
    "Grasp the barbell with a wide grip, slightly wider than shoulder-width apart.": "Agarra la barra con un agarre amplio, ligeramente más ancho que el ancho de los hombros.",
    "Lower the barbell to your chest, keeping your elbows out to the sides.": "Baja la barra hacia tu pecho, manteniendo los codos hacia afuera.",
    "Push the barbell back up to the starting position, fully extending your arms.": "Empuja la barra de vuelta a la posición inicial, extendiendo completamente tus brazos.",
    "Repeat for the desired number of repetitions.": "Repite para el número deseado de repeticiones."
}

traducciones_objetivos = {
    "pectorals": "pectorales",
    "triceps": "tríceps",
    "shoulders": "hombros",
    "core": "núcleo",
    "lats": "dorsales"
}


def llenar_catalogo(apps,schema_editor):
    Ejercicio = apps.get_model('routine_app','Ejercicio')

    url = "https://exercisedb.p.rapidapi.com/exercises/bodyPart/chest"
    querystring = {"limit":"10"}
    headers = {
        'X-RapidAPI-Key': '891b93fa0emsh072b1fbe8965257p128f0ajsn2fee5da1207b',
        'X-RapidAPI-Host': 'exercisedb.p.rapidapi.com'
    }

    response = requests.request("GET", url, headers=headers, params=querystring)

    if response.status_code == 200:
        data = response.json()
        for ejercicio in data:
            instrucciones_traducidas = [traducciones_instrucciones[inst] for inst in ejercicio ['instructions']]
            nuevo_ejercicio = Ejercicio(
                nombre=traducciones_nombres_ejercicios[ejercicio['name']],
                musculo=traducciones_parte_del_cuerpo[ejercicio['bodyPart']],
                equipamento=traducciones_equipo[ejercicio['equipment']],
                instrucciones=" ".join(instrucciones_traducidas),
                imagen=ejercicio['gifUrl'],
                objetivo=traducciones_objetivos[ejercicio['target']]
            )
            nuevo_ejercicio.save()


def revertir_llenar_catalogo(apps,schema_editor):
    Ejercicio = apps.get_model('routine_app','Ejercicio')
    Ejercicio.objects.all().delete()


class Migration(migrations.Migration):

    dependencies = [
        ('routine_app', '0032_alter_ejercicio_musculo_alter_ejercicio_nombre'),
    ]

    operations = [
        migrations.RunPython(llenar_catalogo, revertir_llenar_catalogo)
    ]
