# Generated by Django 5.0.3 on 2024-03-26 22:19

from django.db import migrations
import requests

traducciones_nombres_ejercicios = {
    "band reverse wrist curl": "curl de muñeca inverso con banda",
    "band wrist curl": "curl de muñeca con banda",
    "barbell palms down wrist curl over a bench": "curl de muñeca con palmas hacia abajo con barra sobre banco",
    "barbell palms up wrist curl over a bench": "curl de muñeca con palmas hacia arriba con barra sobre banco",
    "barbell revers wrist curl v. 2": "curl de muñeca inverso v. 2 con barra",
    "barbell reverse wrist curl": "curl de muñeca inverso con barra",
    "barbell standing back wrist curl": "curl de muñeca trasero de pie con barra",
    "barbell wrist curl": "curl de muñeca con barra",
    "barbell wrist curl v. 2": "curl de muñeca v. 2 con barra",
    "cable reverse wrist curl": "curl de muñeca inverso con cable"
}


traducciones_parte_del_cuerpo = {
    "lower arms": "antebrazos",
}

traducciones_objetivos = {
    "forearms": "antebrazos",
    "biceps": "bíceps",
    "triceps": "tríceps",
    "brachialis": "braquial",
    "shoulders": "hombros",
    "wrists": "muñecas"
}


traducciones_equipo = {
    "band": "banda",
    "barbell": "barra",
    "dumbbell": "mancuerna",
    "cable": "cable",
    "machine": "máquina",
    "body weight": "peso corporal",
    "kettlebell": "pesa rusa"  
}


traducciones_instrucciones = {
    # Instrucciones para "band reverse wrist curl"
    "Sit on a bench or chair with your feet flat on the ground.": "Siéntate en un banco o silla con los pies planos en el suelo.",
    "Hold the band with an overhand grip, palms facing down, and wrap it around your fingers.": "Sostén la banda con un agarre por encima, palmas hacia abajo, y envuélvela alrededor de tus dedos.",
    "Rest your forearms on your thighs, with your wrists hanging off the edge.": "Apoya tus antebrazos en tus muslos, con las muñecas colgando del borde.",
    "Slowly curl your wrists upward, squeezing your forearms.": "Flexiona lentamente tus muñecas hacia arriba, apretando tus antebrazos.",
    "Pause for a moment at the top, then slowly lower your wrists back down to the starting position.": "Haz una pausa por un momento en la parte superior, luego baja lentamente tus muñecas de nuevo a la posición inicial.",
    "Repeat for the desired number of repetitions.": "Repite para el número deseado de repeticiones.",
    
    # Instrucciones para "band wrist curl"
    "Hold the band with an overhand grip, palms facing down, and wrap it around your fingers.": "Sostén la banda con un agarre por encima, palmas hacia abajo, y envuélvela alrededor de tus dedos.",
    "Hold the band with both hands, palms facing up, and rest your forearms on your thighs.": "Sujeta la banda con ambas manos, palmas hacia arriba, y apoya los antebrazos en tus muslos.",

    # Instrucciones para "barbell palms down wrist curl over a bench"
    "Sit on a bench with your feet flat on the ground and your forearms resting on your thighs, palms facing down.": "Siéntate en un banco con los pies planos en el suelo y tus antebrazos apoyados en tus muslos, palmas hacia abajo.",
    "Hold a barbell with an overhand grip, hands shoulder-width apart.": "Sujeta una barra con un agarre por encima, manos a la anchura de los hombros.",
    "Lower the barbell towards the ground by flexing your wrists, keeping your forearms stationary.": "Baja la barra hacia el suelo flexionando tus muñecas, manteniendo tus antebrazos inmóviles.",
    "Pause for a moment at the bottom, then slowly raise the barbell back up by extending your wrists.": "Haz una pausa por un momento en la parte inferior, luego eleva lentamente la barra extendiendo tus muñecas.",

     # Instrucciones para "barbell palms up wrist curl over a bench"
    "Sit on a bench with your feet flat on the ground and hold a barbell with an underhand grip, palms facing up.": "Siéntate en un banco con los pies planos en el suelo y sostén una barra con un agarre por debajo, palmas hacia arriba.",
    "Rest your forearms on the bench, allowing your wrists to hang off the edge.": "Apoya tus antebrazos en el banco, permitiendo que tus muñecas cuelguen del borde.",
    "Keeping your forearms stationary, exhale and curl your wrists upwards as far as possible.": "Manteniendo tus antebrazos inmóviles, exhala y flexiona tus muñecas hacia arriba tanto como sea posible.",
    "Hold the contracted position for a brief pause, then inhale and slowly lower the barbell back to the starting position.": "Mantén la posición contraída por una breve pausa, luego inhala y baja lentamente la barra a la posición inicial.",
    
    # Instrucciones para "barbell reverse wrist curl"
    "Sit on a bench with your feet flat on the ground and hold a barbell with an overhand grip, palms facing down.": "Siéntate en un banco con los pies planos en el suelo y sostén una barra con un agarre por encima, las palmas hacia abajo.",
    "Rest your forearms on your thighs, allowing your wrists to hang off the edge.": "Apoya tus antebrazos en tus muslos, permitiendo que tus muñecas cuelguen del borde.",
    "Slowly curl your wrists upward, bringing the barbell towards your body.": "Flexiona lentamente tus muñecas hacia arriba, acercando la barra hacia tu cuerpo.",
    "Pause for a moment at the top, then slowly lower the barbell back down to the starting position.": "Haz una pausa por un momento en la parte superior, luego baja lentamente la barra a la posición inicial.",
    "Repeat for the desired number of repetitions.": "Repite para el número deseado de repeticiones.",

    # Instrucciones para "barbell standing back wrist curl"
    "Stand up straight with your feet shoulder-width apart and hold a barbell with an overhand grip.": "Ponte de pie derecho con los pies separados al ancho de los hombros y sostén una barra con un agarre por encima.",
    "Rest the barbell on the back of your hands with your palms facing down and your fingers pointing towards your body.": "Apoya la barra en el dorso de tus manos con las palmas hacia abajo y los dedos apuntando hacia tu cuerpo.",
    "Keeping your upper arms stationary, exhale and curl your wrists upwards as far as possible.": "Manteniendo tus brazos superiores inmóviles, exhala y curva tus muñecas hacia arriba tanto como sea posible.",
    "Hold the contracted position for a brief pause, then inhale and slowly lower the barbell back to the starting position.": "Mantén la posición contraída por una breve pausa, luego inhala y baja lentamente la barra a la posición inicial.",
    "Repeat for the desired number of repetitions.": "Repite para el número deseado de repeticiones.",

    # Instrucciones para "barbell wrist curl"
    "Sit on a bench with your feet flat on the ground and your forearms resting on your thighs, holding a barbell with an underhand grip.": "Siéntate en un banco con los pies planos en el suelo y tus antebrazos apoyados en tus muslos, sosteniendo una barra con un agarre por debajo.",
    "Allow the barbell to roll down to your fingertips, keeping your wrists straight.": "Permite que la barra se deslice hasta tus dedos, manteniendo las muñecas rectas.",
    "Slowly curl the barbell up towards your forearms by flexing your wrists.": "Flexiona lentamente la barra hacia tus antebrazos flexionando tus muñecas.",
    "Pause for a moment at the top, then slowly lower the barbell back down to the starting position.": "Haz una pausa por un momento en la parte superior, luego baja lentamente la barra a la posición inicial.",
    "Repeat for the desired number of repetitions.": "Repite para el número deseado de repeticiones.",

    # Instrucciones para "barbell wrist curl v. 2"
    "Sit on a bench with your feet flat on the ground and your knees bent.": "Siéntate en un banco con los pies planos en el suelo y las rodillas dobladas.",
    "Hold a barbell with an underhand grip, palms facing up, and your hands shoulder-width apart.": "Sostén una barra con un agarre por debajo, las palmas hacia arriba y las manos separadas al ancho de los hombros.",
    "Rest your forearms on your thighs, allowing your wrists to hang off the edge.": "Apoya tus antebrazos en tus muslos, permitiendo que tus muñecas cuelguen del borde.",
    "Slowly curl your wrists upward, bringing the barbell towards your forearms.": "Flexiona lentamente tus muñecas hacia arriba, acercando la barra hacia tus antebrazos.",
    "Pause for a moment at the top, then slowly lower the barbell back down to the starting position.": "Haz una pausa por un momento en la parte superior, luego baja lentamente la barra a la posición inicial.",
    "Repeat for the desired number of repetitions.": "Repite para el número deseado de repeticiones.",

    # Instrucciones para "cable reverse wrist curl"
    "Attach a cable to a low pulley and sit on a bench facing the cable machine.": "Conecta un cable a una polea baja y siéntate en un banco de frente a la máquina de cable.",
    "Grasp the cable handle with an overhand grip, palms facing down.": "Agarra el mango del cable con un agarre por encima, las palmas hacia abajo.",
    "Rest your forearms on your thighs, with your wrists hanging off the edge.": "Apoya tus antebrazos en tus muslos, con las muñecas colgando del borde.",
    "Keeping your forearms stationary, exhale and curl your wrists upward as far as possible.": "Manteniendo tus antebrazos inmóviles, exhala y curva tus muñecas hacia arriba tanto como sea posible.",
    "Pause for a moment at the top, then inhale and slowly lower your wrists back down to the starting position.": "Haz una pausa por un momento en la parte superior, luego inhala y baja lentamente tus muñecas a la posición inicial.",
    "Repeat for the desired number of repetitions.": "Repite para el número deseado de repeticiones.",

    "Hold a barbell with an overhand grip, palms facing down, and your hands shoulder-width apart.": "Sujeta una barra con agarre prono, palmas hacia abajo, y tus manos separadas al ancho de los hombros.",
}



def llenar_catalogo(apps,schema_editor):
    Ejercicio = apps.get_model('routine_app','Ejercicio')

    url = "https://exercisedb.p.rapidapi.com/exercises/bodyPart/lower arms"
    querystring = {"limit":"10"}
    headers = {
        'X-RapidAPI-Key': '891b93fa0emsh072b1fbe8965257p128f0ajsn2fee5da1207b',
        'X-RapidAPI-Host': 'exercisedb.p.rapidapi.com'
    }

    response = requests.request("GET", url, headers=headers, params=querystring)

    if response.status_code == 200:
        data = response.json()
        for ejercicio in data:
            instrucciones_traducidas = [traducciones_instrucciones[inst] for inst in ejercicio ['instructions']]
            nuevo_ejercicio = Ejercicio(
                nombre=traducciones_nombres_ejercicios[ejercicio['name']],
                musculo=traducciones_parte_del_cuerpo[ejercicio['bodyPart']],
                equipamento=traducciones_equipo[ejercicio['equipment']],
                instrucciones=" ".join(instrucciones_traducidas),
                imagen=ejercicio['gifUrl'],
                objetivo=traducciones_objetivos[ejercicio['target']]
            )
            nuevo_ejercicio.save()


def revertir_llenar_catalogo(apps,schema_editor):
    Ejercicio = apps.get_model('routine_app','Ejercicio')
    Ejercicio.objects.all().delete()


class Migration(migrations.Migration):

    dependencies = [
        ('routine_app', '0033_catalogo_ejercicios_chest'),
    ]

    operations = [
        migrations.RunPython(llenar_catalogo, revertir_llenar_catalogo)
    ]