# Generated by Django 5.0.3 on 2024-03-26 22:19

from django.db import migrations
import requests


# Traducciones de nombres de ejercicios
traducciones_nombres_ejercicios = {
    "ankle circles": "círculos de tobillo",
    "assisted lying calves stretch": "estiramiento de pantorrillas acostado asistido",
    "band single leg calf raise": "elevación de pantorrilla de una sola pierna con banda",
    "band single leg reverse calf raise": "elevación de pantorrilla inversa de una sola pierna con banda",
    "band two legs calf raise - (band under both legs) v. 2": "elevación de pantorrilla de dos piernas con banda",
    "barbell floor calf raise": "elevación de pantorrilla en el suelo con barra",
    "barbell seated calf raise": "elevación de pantorrilla sentado con barra",
    "barbell standing calf raise": "elevación de pantorrilla de pie con barra",
    "barbell standing leg calf raise": "elevación de pantorrilla de pie con barra para una pierna"
}

# Traducciones de parte del cuerpo
traducciones_parte_del_cuerpo = {
    "lower legs": "piernas inferiores",
}


# Traducciones de objetivos
traducciones_objetivos = {
    "calves": "pantorrillas",
    "ankle stabilizers": "estabilizadores del tobillo",
    "hamstrings": "isquiotibiales",
    "glutes": "glúteos",
    "ankles": "tobillos",
    "feet": "pies"
}

# Traducciones de equipo
traducciones_equipo = {
    "body weight": "peso corporal",
    "assisted": "asistido",
    "band": "banda",
    "barbell": "barra"
}


traducciones_instrucciones = {
    # Instrucciones para "ankle circles"
    "Sit on the ground with your legs extended in front of you.": "Siéntate en el suelo con las piernas extendidas frente a ti.",
    "Lift one leg off the ground and rotate your ankle in a circular motion.": "Levanta una pierna del suelo y rota tu tobillo en movimiento circular.",
    "Perform the desired number of circles in one direction, then switch to the other direction.": "Realiza el número deseado de círculos en una dirección, luego cambia a la otra dirección.",
    "Repeat with the other leg.": "Repite con la otra pierna.",
    
    # Instrucciones para "assisted lying calves stretch"
    "Lie on your back with your legs extended.": "Acuéstate boca arriba con las piernas extendidas.",
    "Bend one knee and place your foot flat on the ground.": "Dobla una rodilla y coloca el pie plano en el suelo.",
    "Using your hands or a towel, gently pull your toes towards your body, feeling a stretch in your calf.": "Usando tus manos o una toalla, tira suavemente de tus dedos hacia tu cuerpo, sintiendo un estiramiento en la pantorrilla.",
    "Hold the stretch for 20-30 seconds.": "Mantén el estiramiento durante 20-30 segundos.",
    "Release the stretch and repeat on the other leg.": "Suelta el estiramiento y repite con la otra pierna.",
    
    # Instrucciones para "band single leg calf raise"
    "Stand with your feet hip-width apart and place the band around the ball of your left foot.": "Párate con los pies a la anchura de las caderas y coloca la banda alrededor del balón de tu pie izquierdo.",
    "Hold onto a stable object for balance if needed.": "Sujétate a un objeto estable para mantener el equilibrio si es necesario.",
    "Slowly raise your left heel off the ground, lifting your body weight onto the ball of your foot.": "Levanta lentamente tu talón izquierdo del suelo, elevando tu peso corporal sobre el balón de tu pie.",
    "Pause for a moment at the top, then slowly lower your left heel back down to the starting position.": "Haz una pausa por un momento en la parte superior, luego baja lentamente tu talón izquierdo a la posición inicial.",
    "Repeat for the desired number of repetitions, then switch to the right leg.": "Repite para el número deseado de repeticiones, luego cambia a la pierna derecha.",
    
    # Instrucciones para "band single leg reverse calf raise"
    "Stand with your feet hip-width apart and place the band around the ball of your foot.": "Párate con los pies a la anchura de las caderas y coloca la banda alrededor del balón de tu pie.",
    "Hold onto a stable object for balance.": "Sujétate a un objeto estable para mantener el equilibrio.",
    "Slowly raise your heel off the ground, lifting your body weight onto the ball of your foot.": "Levanta lentamente tu talón del suelo, elevando tu peso corporal sobre el balón de tu pie.",
    "Pause for a moment at the top, then slowly lower your heel back down to the starting position.": "Haz una pausa por un momento en la parte superior, luego baja lentamente tu talón a la posición inicial.",
    "Repeat for the desired number of repetitions, then switch to the other leg.": "Repite para el número deseado de repeticiones, luego cambia a la otra pierna.",
    
    # Instrucciones para "band two legs calf raise - (band under both legs) v. 2"
    "Stand with your feet shoulder-width apart and place a resistance band under both feet.": "Párate con los pies separados al ancho de los hombros y coloca una banda de resistencia bajo ambos pies.",
    "Hold the ends of the band with your hands for stability.": "Sostén los extremos de la banda con tus manos para estabilidad.",
    "Raise your heels off the ground as high as possible, using your calves.": "Levanta tus talones del suelo lo más alto posible, usando tus pantorrillas.",
    "Pause for a moment at the top, then slowly lower your heels back down to the starting position.": "Haz una pausa por un momento en la parte superior, luego baja lentamente tus talones a la posición inicial.",
    "Repeat for the desired number of repetitions.": "Repite para el número deseado de repeticiones.",
    
    # Instrucciones para "barbell floor calf raise"
    "Place a barbell on the floor in front of you.": "Coloca una barra en el suelo frente a ti.",
    "Stand with the balls of your feet on the edge of the barbell, with your heels hanging off.": "Párate con los balones de tus pies sobre el borde de la barra, con los talones colgando.",
    "Hold onto a stable object for balance if needed.": "Sujétate de un objeto estable para mantener el equilibrio si es necesario.",
    "Raise your heels as high as possible, using your calves to lift your body.": "Eleva tus talones lo más alto posible, utilizando tus pantorrillas para levantar tu cuerpo.",
    "Pause for a moment at the top, then slowly lower your heels back down to the starting position.": "Haz una pausa en la parte superior, luego baja lentamente los talones a la posición inicial.",
    "Repeat for the desired number of repetitions.": "Repite para el número deseado de repeticiones.",
    
    # Instrucciones para "barbell seated calf raise"
    "Sit on a bench with your feet flat on the floor and a barbell resting on your thighs.": "Siéntate en un banco con los pies planos en el suelo y una barra descansando en tus muslos.",
    "Place the balls of your feet on a raised platform, such as a block or step.": "Coloca los balones de tus pies en una plataforma elevada, como un bloque o escalón.",
    "Position the barbell across your thighs and hold it securely with your hands.": "Posiciona la barra a lo largo de tus muslos y sujétala de forma segura con tus manos.",
    "Keeping your back straight and your core engaged, lift your heels off the ground by extending your ankles.": "Manteniendo la espalda recta y el core activado, levanta los talones del suelo extendiendo los tobillos.",
    "Pause for a moment at the top, then slowly lower your heels back down to the starting position.": "Haz una pausa en el momento más alto, luego baja lentamente los talones a la posición de inicio.",
    
    # Instrucciones para "barbell standing calf raise"
    "Stand with your feet shoulder-width apart and place a barbell across your upper back.": "Párate con los pies separados al ancho de los hombros y coloca una barra sobre tu espalda superior.",
    "Raise your heels off the ground as high as possible, using only your toes.": "Eleva tus talones del suelo lo más alto posible, usando solo tus dedos de los pies.",
    "Pause for a moment at the top, then slowly lower your heels back down to the starting position.": "Haz una pausa por un momento en el punto más alto, luego baja lentamente los talones a la posición inicial.",
    
    # Instrucciones para "barbell standing leg calf raise"
    "Stand with your feet shoulder-width apart and place a barbell across your upper back.": "Párate con los pies separados al ancho de los hombros y coloca una barra sobre tu espalda superior.",
    "Raise your heels off the ground as high as possible, using your calves.": "Eleva tus talones del suelo lo más alto posible, utilizando tus pantorrillas.",
    "Pause for a moment at the top, then slowly lower your heels back down to the starting position.": "Haz una pausa por un momento en el punto más alto, luego baja lentamente los talones a la posición inicial.",
    "Repeat for the desired number of repetitions.": "Repite para el número deseado de repeticiones.",

    "Lower your heels as far as possible, feeling a stretch in your calves.":"Baja tus talones lo máximo posible, sintiendo un estiramiento en tus pantorrillas.",
    "Raise your heels as high as possible, contracting your calves.": "Levanta tus talones lo más alto posible, contrayendo tus pantorrillas.",
}



def llenar_catalogo(apps,schema_editor):
    Ejercicio = apps.get_model('routine_app','Ejercicio')

    url = "https://exercisedb.p.rapidapi.com/exercises/bodyPart/lower legs"
    querystring = {"limit":"10"}
    headers = {
        'X-RapidAPI-Key': '891b93fa0emsh072b1fbe8965257p128f0ajsn2fee5da1207b',
        'X-RapidAPI-Host': 'exercisedb.p.rapidapi.com'
    }

    response = requests.request("GET", url, headers=headers, params=querystring)

    if response.status_code == 200:
        data = response.json()
        for ejercicio in data:
            instrucciones_traducidas = [traducciones_instrucciones[inst] for inst in ejercicio['instructions']]
            nuevo_ejercicio = Ejercicio(
                nombre=traducciones_nombres_ejercicios[ejercicio['name']],
                musculo=traducciones_parte_del_cuerpo[ejercicio['bodyPart']],
                equipamento=traducciones_equipo[ejercicio['equipment']],
                instrucciones=" ".join(instrucciones_traducidas),
                imagen=ejercicio['gifUrl'],
                objetivo=traducciones_objetivos[ejercicio['target']]
            )
            nuevo_ejercicio.save()


def revertir_llenar_catalogo(apps,schema_editor):
    Ejercicio = apps.get_model('routine_app','Ejercicio')
    Ejercicio.objects.all().delete()


class Migration(migrations.Migration):

    dependencies = [
        ('routine_app', '0034_catalogo_ejercicios_lower_arms'),
    ]

    operations = [
        migrations.RunPython(llenar_catalogo, revertir_llenar_catalogo)
    ]