# Generated by Django 5.0.3 on 2024-03-26 22:19

from django.db import migrations
import requests

traducciones_nombres_ejercicios = {
    "band front lateral raise": "elevación lateral frontal con banda",
    "band front raise": "elevación frontal con banda",
    "band reverse fly": "vuelo inverso con banda",
    "band shoulder press": "prensa de hombros con banda",
    "band standing rear delt row": "remo trasero de deltoides de pie con banda",
    "band twisting overhead press": "prensa sobre la cabeza con torsión con banda",
    "band y-raise": "elevación en Y con banda",
    "barbell front raise": "elevación frontal con barra",
    "barbell one arm snatch": "arrancada con un brazo con barra",
    "barbell rear delt raise": "elevación trasera del deltoides con barra"
}


traducciones_parte_del_cuerpo = {
    "shoulders": "hombros"
}


traducciones_objetivos = {
    "delts": "deltoides",
    "traps": "trapecios",
    "upper back": "parte superior de la espalda",
    "triceps": "tríceps",
    "forearms": "antebrazos",
    "core": "núcleo",
    "rhomboids": "romboides",
    "biceps": "bíceps"
}

traducciones_equipo = {
    "band": "banda",
    "barbell": "barra"
}


traducciones_instrucciones = {
    # Instrucciones para "band front lateral raise"
    "Stand with your feet shoulder-width apart and hold the band in front of your thighs with your palms facing down.": "Párate con los pies a la anchura de los hombros y sostén la banda frente a tus muslos con las palmas hacia abajo.",
    "Keep your arms straight and lift the band up in front of you until your arms are parallel to the ground.": "Mantén los brazos rectos y levanta la banda frente a ti hasta que tus brazos estén paralelos al suelo.",
    "Pause for a moment at the top, then slowly lower the band back down to the starting position.": "Haz una pausa en el punto más alto, luego baja lentamente la banda a la posición inicial.",
    "Repeat for the desired number of repetitions.": "Repite para el número deseado de repeticiones.",

    # Instrucciones para "band front raise"
    "Stand with your feet shoulder-width apart and hold the band in front of your thighs with your palms facing down.": "Párate con los pies a la anchura de los hombros y sostén la banda frente a tus muslos con las palmas hacia abajo.",
    "Keep your arms straight and slowly raise them forward until they are parallel to the ground.": "Mantén los brazos rectos y levántalos lentamente hacia adelante hasta que estén paralelos al suelo.",
    "Pause for a moment at the top, then slowly lower your arms back down to the starting position.": "Haz una pausa en el punto más alto, luego baja lentamente los brazos a la posición inicial.",
    "Repeat for the desired number of repetitions.": "Repite para el número deseado de repeticiones.",

    # Instrucciones para "band reverse fly"
    "Attach the band to a stationary object at chest height.": "Fija la banda a un objeto estacionario a la altura del pecho.",
    "Stand with your feet shoulder-width apart and hold the band with both hands in front of you.": "Párate con los pies a la anchura de los hombros y sostén la banda con ambas manos frente a ti.",
    "Keep your arms straight and lift them out to the sides until they are parallel to the ground.": "Mantén los brazos rectos y elévalos hacia los lados hasta que estén paralelos al suelo.",
    "Squeeze your shoulder blades together at the top of the movement.": "Aprieta las escápulas en el punto más alto del movimiento.",
    "Slowly lower your arms back to the starting position.": "Baja lentamente los brazos a la posición inicial.",
    "Repeat for the desired number of repetitions.": "Repite para el número deseado de repeticiones.",

    # Instrucciones para "band shoulder press"
    "Stand with your feet shoulder-width apart and place the band under your feet.": "Párate con los pies a la anchura de los hombros y coloca la banda bajo tus pies.",
    "Hold the band with your palms facing forward and raise your hands to shoulder height, elbows bent.": "Sostén la banda con las palmas hacia adelante y sube las manos a la altura de los hombros, con los codos doblados.",
    "Press the band overhead, fully extending your arms.": "Presiona la banda sobre la cabeza, extendiendo completamente los brazos.",
    "Pause for a moment at the top, then slowly lower the band back to shoulder height.": "Haz una pausa en el punto más alto, luego baja lentamente la banda a la altura de los hombros.",
    "Repeat for the desired number of repetitions.": "Repite para el número deseado de repeticiones.",

    # Instrucciones para "band standing rear delt row"
    "Stand with your feet shoulder-width apart and place the band under your feet.": "Párate con los pies separados a la anchura de los hombros y coloca la banda bajo tus pies.",
    "Hold the band handles with your palms facing each other and your arms extended in front of you.": "Sostén los mangos de la banda con las palmas enfrentadas y los brazos extendidos frente a ti.",
    "Bend your knees slightly and hinge forward at the hips, keeping your back straight.": "Dobla ligeramente las rodillas e inclínate hacia adelante desde las caderas, manteniendo la espalda recta.",
    "Pull the band towards your chest, squeezing your shoulder blades together.": "Tira de la banda hacia tu pecho, apretando las escápulas.",
    "Pause for a moment at the top, then slowly release the tension and return to the starting position.": "Haz una pausa en el punto más alto, luego libera lentamente la tensión y regresa a la posición inicial.",
    "Repeat for the desired number of repetitions.": "Repite para el número deseado de repeticiones.",

    # Instrucciones para "band twisting overhead press"
    "Stand with your feet shoulder-width apart and place the band under your feet.": "Párate con los pies a la anchura de los hombros y coloca la banda debajo de tus pies.",
    "Hold the band handles at shoulder height with your palms facing forward.": "Sostén los mangos de la banda a la altura de los hombros con las palmas hacia adelante.",
    "Engage your core and press the band overhead, fully extending your arms.": "Activa tu núcleo y presiona la banda sobre la cabeza, extendiendo completamente los brazos.",
    "As you press, twist your torso to one side, keeping your hips stable.": "Mientras presionas, gira tu torso hacia un lado, manteniendo las caderas estables.",
    "Pause for a moment at the top, then return to the starting position.": "Haz una pausa en el punto más alto, luego regresa a la posición inicial.",
    "Repeat the press and twist on the opposite side.": "Repite la presión y giro hacia el lado opuesto.",
    "Continue alternating sides for the desired number of repetitions.": "Continúa alternando los lados para el número deseado de repeticiones.",

    # Instrucciones para "band y-raise"
    "Stand with your feet shoulder-width apart and hold the band in front of your thighs with your palms facing inwards.": "Párate con los pies a la anchura de los hombros y sostén la banda frente a tus muslos con las palmas hacia adentro.",
    "Keep your arms straight and lift them up and out to the sides, forming a 'Y' shape with your body.": "Mantén los brazos rectos y levántalos hacia arriba y hacia los lados, formando una forma de 'Y' con tu cuerpo.",
    "Squeeze your shoulder blades together at the top of the movement.": "Aprieta las escápulas al final del movimiento.",
    "Slowly lower your arms back down to the starting position.": "Baja lentamente los brazos a la posición inicial.",
    "Repeat for the desired number of repetitions.": "Repite para el número deseado de repeticiones.",

    # Instrucciones para "barbell front raise"
    "Stand with your feet shoulder-width apart and hold a barbell in front of your thighs with an overhand grip.": "Párate con los pies a la anchura de los hombros y sostén una barra frente a tus muslos con un agarre por encima.",
    "Keep your arms straight and lift the barbell forward and upward until it reaches shoulder level.": "Mantén los brazos rectos y levanta la barra hacia adelante y hacia arriba hasta que alcance el nivel de los hombros.",
    "Pause for a moment at the top, then slowly lower the barbell back down to the starting position.": "Haz una pausa en el punto más alto, luego baja lentamente la barra a la posición inicial.",
    "Repeat for the desired number of repetitions.": "Repite para el número deseado de repeticiones.",

    # Instrucciones para "barbell one arm snatch"
    "Stand with your feet shoulder-width apart, toes pointing slightly outwards.": "Párate con los pies a la anchura de los hombros, los dedos de los pies ligeramente hacia afuera.",
    "Hold the barbell with an overhand grip, hands slightly wider than shoulder-width apart.": "Sostén la barra con un agarre por encima, las manos un poco más anchas que la anchura de los hombros.",
    "Bend your knees and lower your hips into a squat position, keeping your back straight and chest up.": "Dobla las rodillas y baja las caderas en una posición de cuclillas, manteniendo la espalda recta y el pecho hacia arriba.",
    "Explosively extend your hips, knees, and ankles, driving the barbell upwards.": "Extiende de manera explosiva las caderas, rodillas y tobillos, impulsando la barra hacia arriba.",
    "As the barbell reaches chest level, pull it upwards with your arm, keeping it close to your body.": "A medida que la barra alcance el nivel del pecho, tira de ella hacia arriba con tu brazo, manteniéndola cerca de tu cuerpo.",
    "Rotate your elbow under the barbell and extend your arm fully overhead, locking out your elbow.": "Rota tu codo debajo de la barra y extiende completamente tu brazo por encima de la cabeza, bloqueando tu codo.",
    "Lower the barbell back down to the starting position in a controlled manner.": "Baja la barra a la posición inicial de manera controlada.",
    "Repeat for the desired number of repetitions, then switch arms.": "Repite para el número deseado de repeticiones, luego cambia de brazo.",

    # Instrucciones para "barbell rear delt raise"
    "Stand with your feet shoulder-width apart and hold a barbell with an overhand grip, palms facing down.": "Párate con los pies a la anchura de los hombros y sostén una barra con un agarre por encima, las palmas hacia abajo.",
    "Bend your knees slightly and hinge forward at the hips, keeping your back straight.": "Dobla ligeramente las rodillas e inclínate hacia adelante desde las caderas, manteniendo la espalda recta.",
    "Raise the barbell out to the sides, keeping your arms straight, until they are parallel to the ground.": "Levanta la barra hacia los lados, manteniendo los brazos rectos, hasta que estén paralelos al suelo.",
    "Pause for a moment at the top, then slowly lower the barbell back to the starting position.": "Haz una pausa en el punto más alto, luego baja lentamente la barra a la posición inicial.",
    "Repeat for the desired number of repetitions.": "Repite para el número deseado de repeticiones."
}




def llenar_catalogo(apps,schema_editor):
    Ejercicio = apps.get_model('routine_app','Ejercicio')

    url = "https://exercisedb.p.rapidapi.com/exercises/bodyPart/shoulders"
    querystring = {"limit":"10"}
    headers = {
        'X-RapidAPI-Key': '891b93fa0emsh072b1fbe8965257p128f0ajsn2fee5da1207b',
        'X-RapidAPI-Host': 'exercisedb.p.rapidapi.com'
    }


    response = requests.request("GET", url, headers=headers, params=querystring)

    if response.status_code == 200:
        data = response.json()
        for ejercicio in data:
            instrucciones_traducidas = [traducciones_instrucciones[inst] for inst in ejercicio['instructions']]
            nuevo_ejercicio = Ejercicio(
                nombre=traducciones_nombres_ejercicios[ejercicio['name']],
                musculo=traducciones_parte_del_cuerpo[ejercicio['bodyPart']],
                equipamento=traducciones_equipo[ejercicio['equipment']],
                instrucciones=" ".join(instrucciones_traducidas),
                imagen=ejercicio['gifUrl'],
                objetivo=traducciones_objetivos[ejercicio['target']]
            )
            nuevo_ejercicio.save()


def revertir_llenar_catalogo(apps,schema_editor):
    Ejercicio = apps.get_model('routine_app','Ejercicio')
    Ejercicio.objects.all().delete()


class Migration(migrations.Migration):

    dependencies = [
        ('routine_app', '0035_catalogo_ejercicios_lower_legs'),
    ]

    operations = [
        migrations.RunPython(llenar_catalogo, revertir_llenar_catalogo)
    ]