# Generated by Django 5.0.3 on 2024-03-26 22:19

from django.db import migrations
import requests

traducciones_nombres_ejercicios = {
    "assisted standing triceps extension (with towel)": "extensión de tríceps de pie asistida (con toalla)",
    "assisted triceps dip (kneeling)": "fondos de tríceps asistidos (de rodillas)",
    "band alternating biceps curl": "curl de bíceps alternando con banda",
    "band close-grip push-up": "push-up con agarre cerrado con banda",
    "band concentration curl": "curl de concentración con banda",
    "band one arm overhead biceps curl": "curl de bíceps con un brazo por encima de la cabeza con banda",
    "band side triceps extension": "extensión lateral de tríceps con banda",
    "barbell alternate biceps curl": "curl de bíceps alternado con barra",
    "barbell biceps curl (with arm blaster)": "curl de bíceps con barra (con arm blaster)",
    "barbell close-grip bench press": "press de banca con agarre cerrado con barra"
}

traducciones_partes_del_cuerpo = {
    "upper arms": "brazos superiores"
}

traducciones_objetivos = {
    "triceps": "tríceps",
    "biceps": "bíceps",
    "chest": "pecho",
    "shoulders": "hombros",
    "forearms": "antebrazos"
}

traducciones_equipos = {
    "assisted": "asistido",
    "leverage machine": "máquina de palanca",
    "band": "banda",
    "barbell": "barra"
}

traducciones_instrucciones = {
    "Lie flat on a bench with your feet flat on the ground and your back pressed against the bench.": "Acuéstate en un banco con los pies apoyados en el suelo y la espalda presionada contra el banco.",
    "Grasp the barbell with a close grip, slightly narrower than shoulder-width apart.": "Agarra la barra con un agarre cerrado, ligeramente más estrecho que el ancho de los hombros.",
    "Unrack the barbell and lower it slowly towards your chest, keeping your elbows close to your body.": "Desencaja la barra y bájala lentamente hacia tu pecho, manteniendo los codos cerca de tu cuerpo.",
    "Pause for a moment when the barbell touches your chest.": "Haz una pausa cuando la barra toque tu pecho.",
    "Push the barbell back up to the starting position, fully extending your arms.": "Empuja la barra de vuelta a la posición inicial, extendiendo completamente tus brazos.",
    "Stand up straight with your feet shoulder-width apart and hold a barbell with an underhand grip, palms facing up.": "Ponte derecho con los pies a la anchura de los hombros y sostén una barra con un agarre supino, palmas hacia arriba.",
    "Place your upper arms against the arm blaster, keeping your elbows close to your torso.": "Coloca tus brazos superiores contra el arm blaster, manteniendo los codos cerca de tu torso.",
    "Keeping your upper arms stationary, exhale and curl the weights while contracting your biceps.": "Manteniendo tus brazos superiores fijos, exhala y riza los pesos mientras contraes tus bíceps.",
    "Continue to raise the barbell until your biceps are fully contracted and the bar is at shoulder level.": "Continúa elevando la barra hasta que tus bíceps estén completamente contraídos y la barra esté al nivel de los hombros.",
    "Hold the contracted position for a brief pause as you squeeze your biceps.": "Mantén la posición contraída durante una breve pausa mientras aprietas tus bíceps.",
    "Inhale as you slowly begin to lower the barbell back to the starting position.": "Inhala mientras comienzas a bajar lentamente la barra a la posición inicial.",
    "Repeat for the desired number of repetitions, alternating arms.": "Repite para el número deseado de repeticiones, alternando los brazos.",

     # Instrucciones para "assisted standing triceps extension (with towel)"
    "Stand with your feet shoulder-width apart and hold a towel with both hands behind your head.": "Párate con los pies separados al ancho de los hombros y sostén una toalla con ambas manos detrás de tu cabeza.",
    "Keep your elbows close to your ears and your upper arms stationary.": "Mantén tus codos cerca de tus orejas y tus brazos superiores estacionarios.",
    "Slowly extend your forearms upward, squeezing your triceps at the top.": "Extiende lentamente tus antebrazos hacia arriba, apretando tus tríceps en la parte superior.",
    "Pause for a moment, then slowly lower the towel back down to the starting position.": "Haz una pausa por un momento, luego baja lentamente la toalla a la posición inicial.",
    
    # Instrucciones para "assisted triceps dip (kneeling)"
    "Adjust the machine to your desired weight and height.": "Ajusta la máquina a tu peso y altura deseados.",
    "Kneel down on the pad facing the machine, with your hands gripping the handles.": "Arrodíllate en la almohadilla frente a la máquina, con tus manos agarrando los mangos.",
    "Lower your body by bending your elbows, keeping your back straight and close to the machine.": "Baja tu cuerpo doblando los codos, manteniendo la espalda recta y cerca de la máquina.",
    
    # Instrucciones para "band alternating biceps curl"
    "Stand with your feet shoulder-width apart and hold the band with an underhand grip, palms facing up.": "Párate con los pies a la anchura de los hombros y sostén la banda con un agarre supino, palmas hacia arriba.",
    "Keep your elbows close to your sides and slowly curl one arm up towards your shoulder, squeezing your biceps at the top.": "Mantén tus codos cerca de tus lados y riza lentamente un brazo hacia tu hombro, apretando tus bíceps en la parte superior.",
    
    # Instrucciones para "band close-grip push-up"
    "Place a band around your upper arms, just above the elbows.": "Coloca una banda alrededor de tus brazos superiores, justo por encima de los codos.",
    "Assume a push-up position with your hands directly under your shoulders and your body in a straight line from head to heels.": "Asume una posición de flexión con tus manos directamente debajo de tus hombros y tu cuerpo en una línea recta de la cabeza a los talones.",
    "Bend your elbows and lower your chest towards the ground, keeping your elbows close to your sides.": "Dobla tus codos y baja tu pecho hacia el suelo, manteniendo tus codos cerca de tus costados.",
    
    # Instrucciones para "band concentration curl"
    "Sit on a bench or chair with your legs spread apart and your feet flat on the ground.": "Siéntate en un banco o silla con las piernas separadas y los pies apoyados en el suelo.",
    "Hold one end of the band in your hand and step on the other end with your foot on the same side.": "Sujeta un extremo de la banda con tu mano y pisa el otro extremo con el pie del mismo lado.",
    "Lean forward slightly and rest your elbow on the inside of your thigh, just above the knee.": "Inclínate ligeramente hacia adelante y apoya tu codo en el interior de tu muslo, justo por encima de la rodilla.",
    
    # Instrucciones para "band one arm overhead biceps curl"
    "Hold the other end of the band with your arm fully extended overhead, palm facing forward.": "Sujeta el otro extremo de la banda con tu brazo completamente extendido sobre la cabeza, palma hacia adelante.",
    "Keeping your upper arm stationary, curl your forearm towards your shoulder, squeezing your biceps.": "Manteniendo tu brazo superior estacionario, riza tu antebrazo hacia tu hombro, apretando tus bíceps.",
    
    # Instrucciones para "band side triceps extension"
    "Stand with your feet shoulder-width apart and hold the band with both hands, palms facing down.": "Párate con los pies a la anchura de los hombros y sostén la banda con ambas manos, palmas hacia abajo.",
    "Extend your arms straight out to the sides, keeping them parallel to the ground.": "Extiende tus brazos rectos hacia los lados, manteniéndolos paralelos al suelo.",
    
    # Instrucciones para "barbell alternate biceps curl"
    "Stand up straight with your feet shoulder-width apart and hold a barbell in each hand, palms facing forward.": "Ponte derecho con los pies a la anchura de los hombros y sostén una barra en cada mano, palmas hacia adelante.",
    "Keep your upper arms stationary and exhale as you curl the weights while contracting your biceps.": "Mantén tus brazos superiores estacionarios y exhala mientras rizas los pesos contrayendo tus bíceps.",
    
    # Instrucciones para "barbell biceps curl (with arm blaster)"
    "Place your upper arms against the arm blaster, keeping your elbows close to your torso.": "Coloca tus brazos superiores contra el arm blaster, manteniendo tus codos cerca de tu torso.",

    # Instrucciones para "barbell close-grip bench press"
    "Lie flat on a bench with your feet flat on the ground and your back pressed against the bench.": "Acuéstate en un banco con los pies planos en el suelo y tu espalda presionada contra el banco.",
    "Grasp the barbell with a close grip, slightly narrower than shoulder-width apart.": "Agarra la barra con un agarre cerrado, ligeramente más estrecho que el ancho de los hombros.",
    "Unrack the barbell and lower it slowly towards your chest, keeping your elbows close to your body.": "Desencaja la barra y bájala lentamente hacia tu pecho, manteniendo los codos cerca de tu cuerpo.",
    "Pause for a moment when the barbell touches your chest.": "Haz una pausa por un momento cuando la barra toque tu pecho.",
    "Push the barbell back up to the starting position, fully extending your arms.": "Empuja la barra de vuelta a la posición inicial, extendiendo completamente tus brazos.",
    "Repeat for the desired number of repetitions.": "Repite para el número deseado de repeticiones.",

    "Pause for a moment at the bottom, then push yourself back up to the starting position.": "Haz una pausa por un momento en la parte inferior, luego impúlsate de regreso a la posición inicial.",
    "Lower the arm back down to the starting position and repeat with the other arm.": "Baja el brazo de vuelta a la posición inicial y repite con el otro brazo.",
    "Continue alternating arms for the desired number of repetitions.": "Continúa alternando los brazos por el número deseado de repeticiones.",
    "Push through your palms to extend your arms and return to the starting position.": "Empuja con tus palmas para extender tus brazos y volver a la posición inicial.",
    "With your palm facing up, slowly curl your hand towards your shoulder, keeping your upper arm stationary.": "Con la palma hacia arriba, dobla lentamente tu mano hacia tu hombro, manteniendo el brazo superior inmóvil.",
    "Pause for a moment at the top, then slowly lower your hand back down to the starting position.": "Haz una pausa por un momento en la parte superior, luego baja lentamente tu mano de vuelta a la posición inicial.",
    "Repeat for the desired number of repetitions, then switch sides.": "Repite el número deseado de repeticiones, luego cambia de lado.",
    "Stand with your feet shoulder-width apart and place one end of the band under your foot.": "Párate con los pies separados al ancho de los hombros y coloca un extremo de la banda debajo de tu pie.",
    "Pause for a moment at the top, then slowly lower your forearm back to the starting position.": "Haz una pausa por un momento en la parte superior, luego baja lentamente tu antebrazo de vuelta a la posición inicial.",
    "Repeat for the desired number of repetitions, then switch arms.": "Repite el número deseado de repeticiones, luego cambia de brazo.",
    "Slowly bend your elbows and bring your hands towards your shoulders, keeping your upper arms still.": "Dobla lentamente tus codos y lleva tus manos hacia tus hombros, manteniendo los brazos superiores quietos.",
    "Pause for a moment, then slowly extend your arms back out to the starting position.": "Haz una pausa por un momento, luego extiende lentamente tus brazos de vuelta a la posición inicial.",
    "Continue to raise the barbells until your biceps are fully contracted and the barbells are at shoulder level.": "Continúa elevando las barras hasta que tus bíceps estén completamente contraídos y las barras estén al nivel de los hombros.",
    "Inhale as you slowly begin to lower the barbells back to the starting position.": "Inhala mientras comienzas a bajar lentamente las barras a la posición inicial.",
    "Inhale and slowly begin to lower the barbell back to the starting position.": "Inhala mientras comienzas a bajar",
}




def llenar_catalogo(apps,schema_editor):
    Ejercicio = apps.get_model('routine_app','Ejercicio')

    url = "https://exercisedb.p.rapidapi.com/exercises/bodyPart/upper arms"
    querystring = {"limit":"10"}
    headers = {
        'X-RapidAPI-Key': '891b93fa0emsh072b1fbe8965257p128f0ajsn2fee5da1207b',
        'X-RapidAPI-Host': 'exercisedb.p.rapidapi.com'
    }

    response = requests.request("GET", url, headers=headers, params=querystring)

    if response.status_code == 200:
        data = response.json()
        for ejercicio in data:
            instrucciones_traducidas = [traducciones_instrucciones[inst] for inst in ejercicio['instructions']]
            nuevo_ejercicio = Ejercicio(
                nombre=traducciones_nombres_ejercicios[ejercicio['name']],
                musculo=traducciones_partes_del_cuerpo[ejercicio['bodyPart']],
                equipamento=traducciones_equipos[ejercicio['equipment']],
                instrucciones=" ".join(instrucciones_traducidas),
                imagen=ejercicio['gifUrl'],
                objetivo=traducciones_objetivos[ejercicio['target']]
            )
            nuevo_ejercicio.save()


def revertir_llenar_catalogo(apps,schema_editor):
    Ejercicio = apps.get_model('routine_app','Ejercicio')
    Ejercicio.objects.all().delete()


class Migration(migrations.Migration):

    dependencies = [
        ('routine_app', '0036_catalogo_ejercicios_shoulders'),
    ]

    operations = [
        migrations.RunPython(llenar_catalogo, revertir_llenar_catalogo)
    ]