# Generated by Django 5.0.3 on 2024-04-03 19:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('routine_app', '0037_catalogo_ejercicios_upper_arms'),
    ]

    operations = [
        migrations.AddField(
            model_name='entrenador',
            name='apellido',
            field=models.CharField(default=0, max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='entrenador',
            name='nombre',
            field=models.CharField(default=0, max_length=50),
            preserve_default=False,
        ),
    ]
