# Generated by Django 5.0.3 on 2024-05-29 00:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('routine_app', '0037_catalogo_ejercicios_upper_arms'),
    ]

    operations = [
        migrations.CreateModel(
            name='Compuesta',
            fields=[
                ('id_compuesta', models.AutoField(primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='SeAsigna',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('series', models.IntegerField()),
                ('repeticiones', models.IntegerField()),
                ('peso', models.IntegerField()),
                ('volumen', models.FloatField()),
                ('intensidad', models.FloatField()),
                ('fecha', models.DateField(auto_now_add=True)),
                ('tipo', models.CharField(max_length=50)),
            ],
        ),
        migrations.RemoveField(
            model_name='administrador',
            name='email',
        ),
        migrations.RemoveField(
            model_name='cliente',
            name='email',
        ),
        migrations.AddField(
            model_name='administrador',
            name='apellido',
            field=models.CharField(default=1, max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='administrador',
            name='nombre',
            field=models.CharField(default=1, max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='cliente',
            name='apellido',
            field=models.CharField(default=1, max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='cliente',
            name='nombre',
            field=models.CharField(default=1, max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='entrenador',
            name='apellido',
            field=models.CharField(default=1, max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='entrenador',
            name='nombre',
            field=models.CharField(default=1, max_length=50),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='administrador',
            name='borrado',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='borrado',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='entrenador',
            name='borrado',
            field=models.BooleanField(default=False),
        ),
        migrations.AddConstraint(
            model_name='consume',
            constraint=models.UniqueConstraint(fields=('id_cliente', 'id_alimento'), name='unique_cliente_alimento'),
        ),
        migrations.AddField(
            model_name='compuesta',
            name='id_ejercicio',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='routine_app.ejercicio'),
        ),
        migrations.AddField(
            model_name='compuesta',
            name='id_rutina',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='routine_app.rutina'),
        ),
        migrations.AddField(
            model_name='seasigna',
            name='id_cliente',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='routine_app.cliente'),
        ),
        migrations.AddField(
            model_name='seasigna',
            name='id_ejercicio',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='routine_app.ejercicio'),
        ),
        migrations.AddField(
            model_name='seasigna',
            name='id_rutina',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='routine_app.rutina'),
        ),
        migrations.AddConstraint(
            model_name='compuesta',
            constraint=models.UniqueConstraint(fields=('id_rutina', 'id_ejercicio'), name='unique_compuesta_rutina_ejercicio'),
        ),
        migrations.AddConstraint(
            model_name='seasigna',
            constraint=models.UniqueConstraint(fields=('id_rutina', 'id_ejercicio'), name='unique_seasigna_rutina_ejercicio'),
        ),
        migrations.AddConstraint(
            model_name='seasigna',
            constraint=models.UniqueConstraint(fields=('id_cliente', 'series'), name='unique_cliente_series'),
        ),
        migrations.AddConstraint(
            model_name='seasigna',
            constraint=models.UniqueConstraint(fields=('id_rutina', 'id_cliente'), name='unique_rutina_cliente'),
        ),
        migrations.AddConstraint(
            model_name='seasigna',
            constraint=models.UniqueConstraint(fields=('id_ejercicio', 'series'), name='unique_ejercicio_series'),
        ),
        migrations.AddConstraint(
            model_name='seasigna',
            constraint=models.UniqueConstraint(fields=('id_rutina', 'id_ejercicio', 'id_cliente', 'series'), name='unique_seasigna_rutina_ejercicio_cliente_series'),
        ),
    ]
