# Generated by Django 5.0.3 on 2024-04-03 19:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('routine_app', '0038_entrenador_apellido_entrenador_nombre'),
    ]

    operations = [
        migrations.AddField(
            model_name='administrador',
            name='apellido',
            field=models.CharField(default=0, max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='administrador',
            name='nombre',
            field=models.CharField(default=0, max_length=50),
            preserve_default=False,
        ),
    ]
