# Generated by Django 5.0.3 on 2024-03-26 22:19

from django.db import migrations

def corregir_urls_imagenes(apps, schema_editor):
    Ejercicio = apps.get_model('routine_app', 'Ejercicio')
    ejercicios = Ejercicio.objects.all()
    for ejercicio in ejercicios:
        if ejercicio.imagen and ejercicio.imagen.url.startswith('http://127.0.0.1:8000/https%3A/'):
            # Extraer la parte correcta de la URL
            corrected_url = ejercicio.imagen.replace('http://127.0.0.1:8000/https%3A/', 'https://')
            ejercicio.imagen = corrected_url
            ejercicio.save()

class Migration(migrations.Migration):

    dependencies = [
        ('routine_app', '0038_compuesta_seasigna_remove_administrador_email_and_more'),
    ]

    operations = [
        migrations.RunPython(corregir_urls_imagenes),
    ]
