# Generated by Django 5.0.3 on 2024-05-23 00:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('routine_app', '0039_administrador_apellido_administrador_nombre'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='administrador',
            name='email',
        ),
    ]
