# Generated by Django 5.0.3 on 2024-05-29 02:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('routine_app', '0039_corregir_urls'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ejercicio',
            name='imagen',
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
    ]
