# Generated by Django 5.0.3 on 2024-05-30 00:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('routine_app', '0040_alter_ejercicio_imagen'),
    ]

    operations = [
        migrations.AddField(
            model_name='rutina',
            name='enfoque',
            field=models.CharField(default=1, max_length=50),
            preserve_default=False,
        ),
    ]
