# Generated by Django 5.0.3 on 2024-06-02 15:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('routine_app', '0041_rutina_enfoque'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='seasigna',
            name='unique_seasigna_rutina_ejercicio',
        ),
        migrations.RemoveConstraint(
            model_name='seasigna',
            name='unique_cliente_series',
        ),
        migrations.RemoveConstraint(
            model_name='seasigna',
            name='unique_rutina_cliente',
        ),
        migrations.RemoveConstraint(
            model_name='seasigna',
            name='unique_ejercicio_series',
        ),
        migrations.RemoveConstraint(
            model_name='seasigna',
            name='unique_seasigna_rutina_ejercicio_cliente_series',
        ),
        migrations.RenameField(
            model_name='seasigna',
            old_name='series',
            new_name='serie',
        ),
        migrations.AddConstraint(
            model_name='seasigna',
            constraint=models.UniqueConstraint(fields=('id_rutina', 'id_ejercicio', 'id_cliente', 'serie'), name='unique_seasigna_rutina_ejercicio_cliente_serie'),
        ),
    ]
