# Generated by Django 5.0.3 on 2024-05-28 01:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('routine_app', '0041_cliente_apellido_cliente_nombre_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cliente',
            name='email',
        ),
    ]
