# Generated by Django 5.0.3 on 2024-06-02 15:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('routine_app', '0042_remove_seasigna_unique_seasigna_rutina_ejercicio_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='seasigna',
            name='serie',
        ),
    ]
