# Generated by Django 5.0.3 on 2024-06-02 15:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('routine_app', '0043_remove_seasigna_serie'),
    ]

    operations = [
        migrations.AddField(
            model_name='seasigna',
            name='serie',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
