# Generated by Django 5.0.3 on 2024-06-02 16:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('routine_app', '0044_seasigna_serie'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='seasigna',
            name='intensidad',
        ),
        migrations.RemoveField(
            model_name='seasigna',
            name='tipo',
        ),
        migrations.RemoveField(
            model_name='seasigna',
            name='volumen',
        ),
    ]
