# Generated by Django 5.0.3 on 2024-06-02 20:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('routine_app', '0045_remove_seasigna_intensidad_remove_seasigna_tipo_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='seasigna',
            name='dia',
            field=models.CharField(default=1, max_length=30),
            preserve_default=False,
        ),
    ]
