# Generated by Django 5.0.3 on 2024-10-27 20:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('routine_app', '0046_seasigna_dia'),
    ]

    operations = [
        migrations.AddField(
            model_name='consume',
            name='parte_dia',
            field=models.CharField(default='desayuno', max_length=25),
            preserve_default=False,
        ),
    ]
