# Generated by Django 5.0.3 on 2024-10-27 21:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('routine_app', '0047_consume_parte_dia'),
    ]

    operations = [
        migrations.RenameField(
            model_name='alimento',
            old_name='azucar_total_g',
            new_name='carbohidratos_g',
        ),
        migrations.RenameField(
            model_name='alimento',
            old_name='colesterol_mg',
            new_name='grasa_g',
        ),
        migrations.RemoveField(
            model_name='alimento',
            name='grasa_total_saturada_g',
        ),
        migrations.RemoveField(
            model_name='alimento',
            name='potasio_mg',
        ),
        migrations.RemoveField(
            model_name='alimento',
            name='sodio_mg',
        ),
        migrations.RemoveField(
            model_name='alimento',
            name='total_carbohidratos_g',
        ),
        migrations.RemoveField(
            model_name='alimento',
            name='total_fibra_g',
        ),
        migrations.AddField(
            model_name='consume',
            name='cantidad',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='consume',
            name='fecha',
            field=models.DateField(auto_now_add=True),
        ),
    ]
