# Generated by Django 5.0.3 on 2024-10-27 22:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('routine_app', '0048_rename_azucar_total_g_alimento_carbohidratos_g_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='alimento',
            name='grasa_total_g',
        ),
    ]
