# Generated by Django 5.0.3 on 2024-10-29 20:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('routine_app', '0049_remove_alimento_grasa_total_g'),
    ]

    operations = [
        migrations.AlterField(
            model_name='alimento',
            name='nombre',
            field=models.CharField(max_length=150),
        ),
    ]
