# Generated by Django 5.0.3 on 2024-10-29 20:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('routine_app', '0050_alter_alimento_nombre'),
    ]

    operations = [
        migrations.AlterField(
            model_name='alimento',
            name='calorias',
            field=models.DecimalField(decimal_places=2, max_digits=7),
        ),
        migrations.AlterField(
            model_name='alimento',
            name='carbohidratos_g',
            field=models.DecimalField(decimal_places=2, max_digits=6),
        ),
        migrations.AlterField(
            model_name='alimento',
            name='grasa_g',
            field=models.DecimalField(decimal_places=2, max_digits=6),
        ),
        migrations.AlterField(
            model_name='alimento',
            name='proteina_g',
            field=models.DecimalField(decimal_places=2, max_digits=6),
        ),
    ]
