# Generated by Django 5.0.3 on 2024-10-30 13:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('routine_app', '0051_alter_alimento_calorias_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='alimento',
            name='api_id_referencia',
            field=models.CharField(default=1, max_length=10),
            preserve_default=False,
        ),
    ]
