# Generated by Django 5.0.3 on 2024-10-30 19:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('routine_app', '0052_alimento_api_id_referencia'),
    ]

    operations = [
        migrations.CreateModel(
            name='ParteDia',
            fields=[
                ('id_parte_dia', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=30)),
            ],
        ),
        migrations.RemoveField(
            model_name='consume',
            name='parte_dia',
        ),
        migrations.CreateModel(
            name='Dispone',
            fields=[
                ('id_dispone', models.AutoField(primary_key=True, serialize=False)),
                ('id_alimento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='alimento_dispone', to='routine_app.consume')),
                ('id_cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cliente_dispone', to='routine_app.consume')),
                ('id_parte_dia', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='routine_app.partedia')),
            ],
        ),
        migrations.AddConstraint(
            model_name='dispone',
            constraint=models.UniqueConstraint(fields=('id_cliente', 'id_alimento', 'id_parte_dia'), name='unique_dispone_cliente_alimento_partedia'),
        ),
    ]
