# Generated by Django 5.0.3 on 2024-10-30 20:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('routine_app', '0053_partedia_remove_consume_parte_dia_dispone_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='partedia',
            name='icono',
            field=models.CharField(default=1, max_length=50),
            preserve_default=False,
        ),
    ]
