# Generated by Django 5.0.3 on 2024-10-30 20:12

from django.db import migrations

def generar_parte_dia(apps,schema_editor):
    ParteDia = apps.get_model('routine_app', 'ParteDia')
    partes_dia = ['Desayuno','Almuerzo','Merienda']
    iconos = ['faCoffee','faUtensils','faDrumstickBite']
    for i in range(3):
        ParteDia.objects.create(nombre=partes_dia[i],icono=iconos[i])

class Migration(migrations.Migration):

    dependencies = [
        ('routine_app', '0054_partedia_icono'),
    ]

    operations = [
        migrations.RunPython(generar_parte_dia)
    ]


