# Generated by Django 5.0.3 on 2024-11-01 19:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('routine_app', '0055_completar_parte_dia'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dispone',
            name='id_alimento',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='alimento_dispone', to='routine_app.alimento'),
        ),
        migrations.AlterField(
            model_name='dispone',
            name='id_cliente',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cliente_dispone', to='routine_app.cliente'),
        ),
    ]
