# Generated by Django 5.0.3 on 2024-11-05 03:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('routine_app', '0056_alter_dispone_id_alimento_alter_dispone_id_cliente'),
    ]

    operations = [
    ]
