# Generated by Django 5.0.3 on 2024-11-05 03:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('routine_app', '0057_delete_attribute'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='dispone',
            name='unique_dispone_cliente_alimento_partedia',
        ),
        migrations.RemoveField(
            model_name='alimento',
            name='tamaño_porcion_g',
        ),
        migrations.RemoveField(
            model_name='consume',
            name='cantidad',
        ),
        migrations.AddField(
            model_name='dispone',
            name='cantidad',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='dispone',
            name='fecha',
            field=models.DateField(auto_now_add=True, default='2024-01-01'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='dispone',
            name='tamaño_porcion_g',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
