# Generated by Django 5.0.3 on 2024-11-07 17:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('routine_app', '0058_remove_dispone_unique_dispone_cliente_alimento_partedia_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dispone',
            name='tamaño_porcion_g',
            field=models.CharField(max_length=50),
        ),
    ]
