# Generated by Django 5.0.3 on 2024-11-09 15:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('routine_app', '0059_alter_dispone_tamaño_porcion_g'),
    ]

    operations = [
        migrations.AlterField(
            model_name='seasigna',
            name='fecha',
            field=models.DateField(),
        ),
    ]
