# Generated by Django 5.0.3 on 2024-11-09 16:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('routine_app', '0060_alter_seasigna_fecha'),
    ]

    operations = [
    ]
