# Generated by Django 5.0.3 on 2024-11-09 16:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('routine_app', '0061_delete_attribute'),
    ]

    operations = [
        migrations.AlterField(
            model_name='seasigna',
            name='fecha',
            field=models.DateField(auto_now_add=True),
        ),
    ]
