# Generated by Django 4.2.7 on 2024-03-12 21:18

from django.db import migrations

def crear_niveles_gym(apps,schema_editor): #apps define una función que será usada para añadir datos iniciales a la BD 
    print("La función se ejecutó")
    NivelGym = apps.get_model('routine_app', 'nivelGym') 
    niveles = ['Principiante','Intermedio','Avanzado']
    for nivel in niveles:
        NivelGym.objects.create(nombre = nivel)

def revertir_creacion_niveles(apps, schema_editor):
    NivelGym = apps.get_model('routine_app', 'nivelGym')
    NivelGym.objects.filter(nombre__in=['Principiante', 'Intermedio', 'Avanzado']).delete()
class Migration(migrations.Migration):

    dependencies = [
        ('routine_app', '0002_alter_alimento_calorias'), #migraciones que deben aplicarse antes de la actual
    ]

    operations = [
        migrations.RunPython(crear_niveles_gym, revertir_creacion_niveles), #Se ejecutará cuando se aplique la migración 
    ]
