# Generated by Django 4.2.7 on 2024-03-12 23:39

from django.db import migrations

def crear_niveles_actividad(apps,schema_editor):
    
    NivelActividad = apps.get_model('routine_app', 'nivelActividad')
    niveles = ['Sedentario','Ligeramente activo','Moderadamente activo','Muy activo','Extra activo']
    for nivel in niveles:
        NivelActividad.objects.create(nombre = nivel)

def revertir_creacion_niveles(apps,schema_editor):
    NivelActividad = apps.get_model('routine_app','nivelActividad')
    NivelActividad.objects.filter(nombre__in=['Sedentario','Ligeramente activo','Moderadamente activo','Muy activo','Extra activo']).delete()

class Migration(migrations.Migration):

    dependencies = [
        ('routine_app', '0003_llenar_niveles_gym'),
    ]

    operations = [
        migrations.RunPython(crear_niveles_actividad, revertir_creacion_niveles)
    ]
