# Generated by Django 4.2.7 on 2024-03-13 00:11

from django.db import migrations


def crear_objetivos (apps,schema_editor):
    Objetivo = apps.get_model('routine_app','Objetivo')
    objetivos = ['Perder peso','Ganar masa muscular','Mantener peso']
    for objetivo in objetivos:
        Objetivo.objects.create(nombre = objetivo)

def deshacer_objetivos (apps,schema_editor):
    Objetivo = apps.get_model('routine_app','Objetivo')
    Objetivo.objects.filter(nombre__in=['Perder peso','Ganar masa muscular','Mantener peso']).delete()


class Migration(migrations.Migration):

    dependencies = [
        ('routine_app', '0005_llenar_generos'),
    ]

    operations = [
        migrations.RunPython(crear_objetivos,deshacer_objetivos),
    ]
