# Generated by Django 4.2.7 on 2024-03-12 23:39
from django.core.management.base import BaseCommand
from routine_app.models import NivelActividad


class Command(BaseCommand):
    help = 'Create initial activity levels'

    def handle(self,*args, **kwargs):
        activity_levels = ['Sedentario','Ligeramente activo','Moderadamente activo','Muy activo','Extra activo']
        created_count = 0

        for level in activity_levels:
            obj,created = NivelActividad.objects.get_or_create(nombre=level)
            if created:
                created_count += 1

        self.stdout.write(self.style.SUCCESS(f'{created_count} levels created successfully!'))
    



        
        