# Generated by Django 5.0.3 on 2024-10-30 20:12

# Generated by Django 4.2.7 on 2024-03-13 00:11


from django.core.management.base import BaseCommand
from routine_app.models import ParteDia

class Command(BaseCommand):
    help = 'Create objectives'

    def handle(self,*args, **kwargs):
        partes_dia = ['Desayuno','Almuerzo','Merienda']
        iconos = ['faCoffee','faUtensils','faDrumstickBite']
        created_count = 0
        updated_count = 0
        for i in range(3):
            obj, created = ParteDia.objects.get_or_create(nombre=partes_dia[i], defaults={'icono':iconos[i]})
            if created:
                created_count += 1
            else:
                self.stdout.write(self.style.SUCCESS( f'{updated_count} genres updated successfully!'))
        self.stdout.write(self.style.SUCCESS( f'{created_count} genres created successfully!'))


    