# Generated by Django 4.2.7 on 2024-03-13 00:11


from django.core.management.base import BaseCommand
from routine_app.models import Objetivo

class Command(BaseCommand):
    help = 'Create objectives'

    def handle(self,*args, **kwargs):
        objectives = ['Perder peso','Ganar masa muscular','Mantener peso']
        created_count = 0

        for objective in objectives:
            obj,created = Objetivo.objects.get_or_create(nombre=objective)
            if created:
                created_count += 1
        
        self.stdout.write(self.style.SUCCESS(
            f'{created_count} genres created successfully!'
        ))

