"""
Django settings for gym_project project.

Generated by 'django-admin startproject' using Django 5.0.3.

For more information on this file, see
https://docs.djangoproject.com/en/5.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.0/ref/settings/
"""

from pathlib import Path
import os

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-pqpluknjk)4bux^w)@1wyiznic#9^xmr#v+aye6)#+h004uad('

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = []



# Application definition

INSTALLED_APPS = [
    'modeltranslation',
    'routine_app',
    'corsheaders',
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'rest_framework',
    'rest_framework.authtoken',
]

MIDDLEWARE = [

    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    "corsheaders.middleware.CorsMiddleware",
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'gym_project.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'gym_project.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.0/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.postgresql_psycopg2',
        'NAME': 'AppGym3',
        'USER': 'postgres',
        'PASSWORD': 'awayouname11',
        'HOST': 'localhost',  
        'PORT': '5432',
    }      
}

# Password validation
# https://docs.djangoproject.com/en/5.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.0/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.0/howto/static-files/

STATIC_URL = 'static/'

# Default primary key field type
# https://docs.djangoproject.com/en/5.0/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'
CORSALLOWEDORIGINS = []
CORS_ALLOWED_ORIGINS = [
    "http://localhost:3000",  # Reemplaza con la URL de tu frontend React
]


FATSECRET_API_KEY = os.getenv('FATSECRET_API_KEY', '940907e4c1msh2523358c0fb13dep15b731jsnfd364151b589')
FATSECRET_AUTH_TOKEN = os.getenv('FATSECRET_AUTH_TOKEN', "Bearer eyJhbGciOiJSUzI1NiIsImtpZCI6IjEwOEFEREZGRjZBNDkxOUFBNDE4QkREQTYwMDcwQzE5NzNDRjMzMUUiLCJ0eXAiOiJhdCtqd3QiLCJ4NXQiOiJFSXJkX19ha2tacWtHTDNhWUFjTUdYUFBNeDQifQ.eyJuYmYiOjE3MzA0ODk0NDksImV4cCI6MTczMDU3NTg0OSwiaXNzIjoiaHR0cHM6Ly9vYXV0aC5mYXRzZWNyZXQuY29tIiwiYXVkIjoiYmFzaWMiLCJjbGllbnRfaWQiOiIyYjBmYzk0ZmUyMDE0MzJkOTdlMDQwMzkyOWFhMTQ1OSIsInNjb3BlIjpbImJhc2ljIl19.EXDsvLa7Nhm-_FuggXNRH2uxmGDIDNnxpfjzfi-6yCXwCwR4_nuxvJQ90tAvDS74Xf05E5pWbZP6Xl97YEZZw0_HBLIEnf_aaEz70TmtYuKUQL4ujpMuyWH6sh-F02Yh8U3q2Nn80Ik4NqQlEs9OsAQW6KHxdCJYETvAzZrw998b7gcMxoH8V_BVO0l0u9CytH3H6FX8Eet6zIjtRFrAxZBi65ive_otQ6RnlWftd9M0SxH-9L3KHVG48n32XBR6lx0Y0tIKd2VAtNprVB7qeOb04UEFhnLI9TXURV8E-SYrl7Yw0BAQhNyrSBlPZmAJzZXEZfWQeDWZOMTDs7M9KZXAHqbY2cQ5OcFOtgcu5JpqH_mQFFpeAXLXUoFzE_DlgycxV5zHKwbivL8qfujBXTdSAdfMhWdjPi4mXTtMVpysaPNQEvPuJse6lGlnB-CG_NHS9H3B5GteS3vIOUaAEFdciE7ztqmrpeGGcRZkz80suSjTbFVKe3bdym8Fa6k04d3rSkfr01bB6tjU569jTAvoXLydtKg-W9ug3PUt2x4qpFAi52ZKras2LVMnJT0lmx4C0P6u-JpKP6C7hOgMxITFCuhY5h4Tx7B6FXbCiihXJe_qScgUlxWxeD-KaWQDgfe5EuVUWLHMsdE-IHkTc91Eb40weDMulgFhpVdxCjI")



