"""
Django settings for gym_project project.

Generated by 'django-admin startproject' using Django 5.0.3.

For more information on this file, see
https://docs.djangoproject.com/en/5.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.0/ref/settings/
"""

from pathlib import Path
import os
import environ
from datetime import datetime
import pytz
import dj_database_url

# Build paths inside the project like this: BASE_DIR / 'subdir'.
# Base directory
BASE_DIR = Path(__file__).resolve().parent.parent
env = environ.Env()
environ.Env.read_env()


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
#SECRET_KEY = 'django-insecure-pqpluknjk)4bux^w)@1wyiznic#9^xmr#v+aye6)#+h004uad('
SECRET_KEY = env('SECRET_KEY', default='unsafe-default-key')

# SECURITY WARNING: don't run with debug turned on in production!
#DEBUG = True
DEBUG = 'RENDER' not in os.environ

# https://docs.djangoproject.com/en/3.0/ref/settings/#allowed-hosts
ALLOWED_HOSTS = [    
    '127.0.0.1',
    'localhost',
    '192.168.100.11',
    '1acf-2800-bf0-2420-13c-75ad-f115-289b-df2a.ngrok-free.app', ] # Add your ngrok URL

RENDER_EXTERNAL_HOSTNAME = os.environ.get('RENDER_EXTERNAL_HOSTNAME')
if RENDER_EXTERNAL_HOSTNAME:
    ALLOWED_HOSTS.append(RENDER_EXTERNAL_HOSTNAME)

#ALLOWED_HOSTS = ['192.168.100.11', 'localhost', '127.0.0.1']

REST_FRAMEWORK = {
    'DEFAULT_AUTHENTICATION_CLASSES': (
        'rest_framework_simplejwt.authentication.JWTAuthentication',
    )
}
 

# Application definition

INSTALLED_APPS = [
    'modeltranslation',
    'routine_app',
    'corsheaders',
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'rest_framework',
    'rest_framework.authtoken',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'whitenoise.middleware.WhiteNoiseMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    "corsheaders.middleware.CorsMiddleware",
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'gym_project.urls'

CSRF_TRUSTED_ORIGINS = [
    "http://localhost:3000",  # For local development on your computer
    "http://192.168.100.11:3000",  # For access from your mobile device
]


TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [os.path.join(BASE_DIR, 'templates')],  # Add this line
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'gym_project.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.0/ref/settings/#databases

if 'RENDER' in os.environ:
    # 🔒 Producción (Render)
    DATABASES = {
        'default': dj_database_url.config(
            conn_max_age=600,
            ssl_require=True
        )
    }
else:
    # 🧪 Local
    DATABASES = {
        'default': {
            'ENGINE': 'django.db.backends.postgresql',
            'NAME': 'AppGym6',
            'USER': 'postgres',
            'PASSWORD': 'awayouname11',
            'HOST': 'localhost',
            'PORT': '5432',
        }
    }


#DATABASES = {
    #'default': {
        #'ENGINE': 'django.db.backends.postgresql',
        #'NAME': 'app_gym_db',
        #'USER': 'admin_gym',
        #'PASSWORD': '2CJrFsSJqVM46AnX4wkheEFXOEqWvryr',
        #'HOST': 'dpg-d0n9fvuuk2gs73bnh840-a.oregon-postgres.render.com',
        #'PORT': '5432',
    #}
#}




#DATABASES = {
    #'default': {
        #'ENGINE': 'django.db.backends.postgresql_psycopg2',
        #'NAME': 'AppGym6',
        #'USER': 'postgres',
        #'PASSWORD': 'awayouname11',
        #'HOST': 'localhost',  
        #'PORT': '5432',
    #}
#}

# Password validation
# https://docs.djangoproject.com/en/5.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.0/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'America/Guayaquil'  # Ecuador's timezone

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.0/howto/static-files/

STATIC_URL = 'static/'


# This production code might break development mode, so we check whether we're in DEBUG mode
if not DEBUG:
    STATIC_ROOT = os.path.join(BASE_DIR, 'staticfiles')
    STATICFILES_STORAGE = 'whitenoise.storage.CompressedManifestStaticFilesStorage'

# Default primary key field type
# https://docs.djangoproject.com/en/5.0/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'
CORSALLOWEDORIGINS = []
CORS_ALLOWED_ORIGINS = [
    "https://app-45ljvpnqe-sebasm3690s-projects.vercel.app",   # Replace with your Vercel domain
    "http://localhost:3000",  # Reemplaza con la URL de tu frontend React
    "http://192.168.100.11:3000",  # Add this line
]

CSRF_TRUSTED_ORIGINS = [
    "https://app-45ljvpnqe-sebasm3690s-projects.vercel.app",
    "http://localhost:3000",
    "http://192.168.100.11:3000",
]

CORS_ALLOW_ALL_ORIGINS = True

CACHES = {
    'default': {
        'BACKEND': 'django_redis.cache.RedisCache',
        'LOCATION': 'redis://127.0.0.1:6379/1',
        'OPTIONS': {
            'CLIENT_CLASS': 'django_redis.client.DefaultClient',
            'IGNORE_EXCEPTIONS': True,  # Continue without caching if Redis fails
        },
        'KEY_PREFIX': 'routine_app',
    }
}



# Initialize environment variables
env = environ.Env(
    DEBUG=(bool, False)  # Default value for DEBUG is False
)

# Load the .env file
environ.Env.read_env(os.path.join(BASE_DIR, '.env'))


# Example environment variable usage
DEBUG = env('DEBUG')
FATSECRET_API_KEY = env('FATSECRET_API_KEY')
FATSECRET_CLIENT_ID = env('FATSECRET_CLIENT_ID')
FATSECRET_CLIENT_SECRET = env('FATSECRET_CLIENT_SECRET')

#Frontend deploy url
FRONTEND_URL = env("FRONTEND_URL", default="https://app-gym-wheat.vercel.app/")

# Media files configuration
MEDIA_URL = '/media/'  # URL path to access media files
MEDIA_ROOT = BASE_DIR / "media"


# Verify Ecuador timezone during startup
ecuador_timezone = pytz.timezone('America/Guayaquil')
ecuador_time = datetime.now(ecuador_timezone)
print(f"Ecuador timezone datetime on startup: {ecuador_time}")


EMAIL_BACKEND = 'django.core.mail.backends.smtp.EmailBackend'
EMAIL_HOST = 'smtp.gmail.com'
EMAIL_PORT = 587
EMAIL_USE_TLS = True
EMAIL_HOST_USER = 'sebasm6004@gmail.com'
EMAIL_HOST_PASSWORD = 'bjnn toit gggb lcjk'
