"""
Django settings for gym_project project.

Generated by 'django-admin startproject' using Django 5.0.3.

For more information on this file, see
https://docs.djangoproject.com/en/5.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.0/ref/settings/
"""

from pathlib import Path
import os

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-pqpluknjk)4bux^w)@1wyiznic#9^xmr#v+aye6)#+h004uad('

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = []



# Application definition

INSTALLED_APPS = [
    'modeltranslation',
    'routine_app',
    'corsheaders',
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'rest_framework',
    'rest_framework.authtoken',
]

MIDDLEWARE = [

    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    "corsheaders.middleware.CorsMiddleware",
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'gym_project.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'gym_project.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.0/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.postgresql_psycopg2',
        'NAME': 'AppGym5',
        'USER': 'postgres',
        'PASSWORD': 'awayouname11',
        'HOST': 'localhost',  
        'PORT': '5432',
    }      
}

# Password validation
# https://docs.djangoproject.com/en/5.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.0/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.0/howto/static-files/

STATIC_URL = 'static/'

# Default primary key field type
# https://docs.djangoproject.com/en/5.0/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'
CORSALLOWEDORIGINS = []
CORS_ALLOWED_ORIGINS = [
    "http://localhost:3000",  # Reemplaza con la URL de tu frontend React
]


FATSECRET_API_KEY = os.getenv('FATSECRET_API_KEY', '940907e4c1msh2523358c0fb13dep15b731jsnfd364151b589')
FATSECRET_AUTH_TOKEN = os.getenv('FATSECRET_AUTH_TOKEN', "Bearer eyJhbGciOiJSUzI1NiIsImtpZCI6IjEwOEFEREZGRjZBNDkxOUFBNDE4QkREQTYwMDcwQzE5NzNDRjMzMUUiLCJ0eXAiOiJhdCtqd3QiLCJ4NXQiOiJFSXJkX19ha2tacWtHTDNhWUFjTUdYUFBNeDQifQ.eyJuYmYiOjE3MzEwNzYyNTUsImV4cCI6MTczMTE2MjY1NSwiaXNzIjoiaHR0cHM6Ly9vYXV0aC5mYXRzZWNyZXQuY29tIiwiYXVkIjoicHJlbWllciIsImNsaWVudF9pZCI6IjJiMGZjOTRmZTIwMTQzMmQ5N2UwNDAzOTI5YWExNDU5Iiwic2NvcGUiOlsicHJlbWllciJdfQ.IKutJgzAIbx1zz9BIbMQud0RURcXI1A7xF_AsuOSgGW7-ZEyDAxdp56Vc_VS4HO5Avamy-M5zBotKJZWwzVUup_dn8pJPM0G5XzDHbwE5_FtfMqP8-I9GwanNlWZH5sIHWIl-yb9AdzmzBh5HDTwzP0h_6u4A-pNls8PdZIPRqqG7qoV1_6i2G9_ZtMiDod03cjFptoNraLBbmWdI9PTzEEQJZKGqi7Eef2WuB5hBXufMIF_upH0fvL1F2AMk79WHHuy1WgoKu2bwhP4o9gU69D58VuJzYmpum9xUkCr9NVRo6jzdgXRXdytJl7IWWXwJ3_pYb-_ThUBzY0TintrIhNtjmkOWV-H5Y8hu4pmNuuR7O2pQI_aPaiuCNjzMk38nlzc2vVkkdgSddsYAoCEbxaSguWkJRfXJWCChdpcwb_gfK-ADZlbOGekNObL_ofqMxxyDT2_uaO6Snpf4dJDnBERBp8qLbA9WfRFPJ2IwiSU5FUE8XiiWA9scOvWvPNE4k0WiNt_sXJxnYDq1tE31pqX3WRLQnixXZXathJlYVWvw_VcnPl52ncNpdtt6PvsDh8e51jLwamaDlyxLLHtqxjxbUykLGnNlL7ShUhj95PCHK1fD7wqy5Q2IL_H_4ahcD5cCmVbqTidB7D7w4aWk7H69klIwsVApMCAP7RaON8")



